### ISSUE TITLE
HGLRC SPECTER F405V2 Target Needed

### ISSUE THREAD

**Issue by enterobotica** [emuflight/EmuFlight#1029]
**Vendor/Model**
HGLRC Specter F405 V2

* Please provide the target name.
HGLRCF405V2

* Please provide vendor and model of the FC.
HGLRC SPECTER F460 STACK

* Please provide a link to the vendor specifications.
https://www.hglrc.com/products/hglrc-specter-f460-stack-for-fpv-racing-drone-freestyle

**CLI dump or Unified Target**
https://github.com/betaflight/unified-targets/blob/master/configs/default/HGLR-HGLRCF405V2.config

**Comment by nerdCopter** [comment]
Analog or HD?
Only the BMP270 version of the Baro will work (The DPS310 will not as we do not have working drivers). Do you you need magnetometer?

**Comment by enterobotica** [comment]
I'm using ANALOG VTX (XF5804 pro 5.8 GHz)
BARO: BMP280
I have a magnetometer but it is not a priority [LIS2MDL](https://robu.in/product/smartelex-lis2mdl-triple-axis-magnetometer/?gad_source=1&gclid=CjwKCAjw5v2wBhBrEiwAXDDoJeadvV0-HbGnKr_JOi83X3rkENRu8VKbqEKi2pFXuPGkaMB3gxf7NhoCzDAQAvD_BwE) 
GPS: [HGLRC M100 MINI](https://www.hglrc.com/products/hglrc-m100_mini-gps)

Thanks for your response, I appreciate your effort :)

**Comment by nerdCopter** [comment]
please test [EmuFlight_0.4.2_HGLRCF405V2_Build_dbcc5821a.hex.zip](https://github.com/emuflight/EmuFlight/files/15015387/EmuFlight_0.4.2_HGLRCF405V2_Build_dbcc5821a.hex.zip)

  - [Yes/No/Untested] hex Flash & subsequent USB connect
  - [Yes/No/Untested] Gyro 
  - [Yes/No/Untested] Accelerometer
  - [Yes/No/Untested] Is the Serial Count correct? (Ports tab UARTs)
  - [Yes/No/Untested] Motors
  - [Yes/No/Untested] Onboard ADC
  - [Yes/No/Untested] OSD (analog)
  - [Yes/No/Untested] Smart Audio or Tramp controls
  - [Yes/No/Untested] Beeper/Alarm switch
  - [Yes/No/Untested] Barometer
  - [Yes/No/Untested] Blackbox  flash-chip/sdcard
  - [Yes/No/Untested] LED Strip
  - [Yes/No/Untested] GPS
  - [Yes/No/Untested] BlueTooth (if applicable)

**Comment by nerdCopter** [comment]
let me know results so that i can merge/release this target.

**Comment by enterobotica** [comment]
I installed the hex file today, I got all motors spinning but still figuring out how to change motor order in CLI. My board is upside down as it is a 3.5 inch cinewhoop. Here is what I could see after my install:


[**Yes**/No/Untested] hex Flash & subsequent USB connect
[**Yes**/No/Untested] Gyro
[**Yes**/No/Untested] Accelerometer
[**Yes**/No/Untested] Is the Serial Count correct? (Ports tab UARTs)
[**Yes**/No/Untested] Motors
[Yes/No/**Untested**] Onboard ADC
[Yes/No/**Untested**] OSD (analog)
[Yes/No/**Untested**] Smart Audio or Tramp controls
[Yes/No/**Untested**] Beeper/Alarm switch
[Yes/No/**Untested**] Barometer
[Yes/No/**Untested**] Blackbox flash-chip/sdcard
[**Yes**/No/Untested] LED Strip
[Yes/No/**Untested**] GPS
[Yes/No/**Untested**] BlueTooth (if applicable)


I'll keep you posted with further updates.

**Comment by nerdCopter** [comment]
https://www.youtube.com/watch?v=4G0SZ4jUVw0
https://www.youtube.com/watch?v=RMzeTf5mBeE

**Comment by nerdCopter** [comment]
actually, might just need Gyro/Accel FLIP. i would try such before motor resources.
example, i dont know which one
![image](https://github.com/emuflight/EmuFlight/assets/56646290/10d6767b-8c19-4369-b51f-cf7c321373ba)

**Comment by enterobotica** [comment]
I wasn't able to get the right motor mapping with sensor alignment, went ahead with remapping in CLI and it worked great. Had my first flight, filtering needs to be done better now, do we have any resources to get it done right?

Also,
How to know if Barometer is working?
How to check onboard ADC?

[EMUF_cli_20240418_231122.txt](https://github.com/emuflight/EmuFlight/files/15028729/EMUF_cli_20240418_231122.txt)
[Yes] hex Flash & subsequent USB connect
[Yes] Gyro
[Yes] Accelerometer
[Yes] Is the Serial Count correct? (Ports tab UARTs)
[Yes] Motors
[Untested] Onboard ADC
[Yes] OSD (analog)
[Yes] Smart Audio or Tramp controls
[Yes] Beeper/Alarm switch
[Untested] Barometer
[Yes] Blackbox flash-chip/sdcard
[Yes] LED Strip
[Yes] GPS
[Untested] BlueTooth (if applicable)

**Comment by nerdCopter** [comment]
This is my tuning over-view: https://hackmd.io/@nerdCopter/HkZjwid9q , maybe a little outdated. i've been setting my filters, then setting 1 single dynamic-filter notch count with a fairly narrow Q on gyro and a littler wider on D and pretty much good to go in almost all cases.

If you getting Baro data, good enough.
![image](https://github.com/emuflight/EmuFlight/assets/56646290/aeb6ec38-769f-4ce5-bbf8-988d3a99e7d2)

If you getting voltage data, good enough. LiPo plugged should be near actual. may need tuning. 
![image](https://github.com/emuflight/EmuFlight/assets/56646290/6f77f641-6e63-442e-b76d-445a51a66b4c)

**Comment by nerdCopter** [comment]
Join Emuflight discord for tuning help https://discord.gg/BWqgBg3 

i have a 5" SourceOne V5 w/ icm42688p that flies near perfect with this:
![image](https://github.com/emuflight/EmuFlight/assets/56646290/6fa0aedf-861c-4d1a-b177-1a780c91cf25)
![image](https://github.com/emuflight/EmuFlight/assets/56646290/a35e13f5-dd61-4b92-8f42-1ad526f71e4a)
![image](https://github.com/emuflight/EmuFlight/assets/56646290/d654142b-47ac-46ac-ac1c-e72fc3f0085b)

**Comment by enterobotica** [comment]
[Yes] Barometer
[Yes] Onboard ADC

Thanks for your prompt support nerdcopter, for all the resources, I'll follow these and let you know how it pans out.

Please let me know if I can still share updates or this thread needs to be closed.

**Comment by nerdCopter** [comment]
i will merge the target and close this ticket, thank you kindly!
