### ISSUE TITLE
foxeer f722 v4 some bugs

### ISSUE THREAD

**Issue by superLi88** [emuflight/EmuFlight#1070]

**Comment by nerdCopter** [comment]
> 
![image](https://github.com/emuflight/EmuFlight/assets/56646290/18d1b533-a8e1-4ecf-bc65-32b1b29dc08b)

did you solve? i dont know about ground-station.  emulfight is a butterflight fork, which is essentially a betaflight 3.5.7 fork.

**Comment by nerdCopter** [comment]
okay i see #1071 , closing #1070.
