### ISSUE TITLE
fix "cinematic setpoint"

### ISSUE THREAD

**Issue by gretel** [emuflight/EmuFlight#112]

**Comment by Quick-Flash** [comment]
In the works. Have already started that process.

**Comment by gretel** [comment]
how is it going?

**Comment by Quick-Flash** [comment]
I think I've got it finished. Just thinking that a rename of a few things is in order to make this sound less intimidating.

**Comment by gretel** [comment]
dont intimidate.

**Comment by gretel** [comment]
guess it's fixed or sth.
