### ISSUE TITLE
Need Mode 2 stick functions work on EmuFlight

### ISSUE THREAD

**Issue by FrankFPV** [emuflight/EmuFlight#143]
Mode 2 stick functions are good for whoops, I hope it can be use in the future with EmuFlight.
Thanks.

**Comment by gretel** [comment]
i am flying mode 2, no change required.

**Comment by FrankFPV** [comment]
> i am flying mode 2, no change required.

I am saying of mode 2 stick functions
![7C14C824-FC54-4755-BB91-D41D215E3B7F](https://user-images.githubusercontent.com/62689009/77802305-891d1f00-70b5-11ea-9f49-724255e5b9e6.png)

**Comment by Quick-Flash** [comment]
> > i am flying mode 2, no change required.
> 
> I am saying of mode 2 stick functions
> ![7C14C824-FC54-4755-BB91-D41D215E3B7F](https://user-images.githubusercontent.com/62689009/77802305-891d1f00-70b5-11ea-9f49-724255e5b9e6.png)

I am pretty sure that we already do this... I think i have used this before... Can you verify?

**Comment by gretel** [comment]
as i said, this is working fine on mode 2.
