### ISSUE TITLE
Add hglrc f411 target for 0.2.0 firmware.

### ISSUE THREAD

**Issue by trnnwnnhe** [emuflight/EmuFlight#166]
Can you do it?

**Comment by gretel** [comment]
can you do it?

**Comment by nerdCopter** [comment]
@trnnwnnhe target `HGLRCF411` will be in firmware 0.3.0 release.

**Comment by trnnwnnhe** [comment]
for 0.2.0

**Comment by nerdCopter** [comment]
@trnnwnnhe, It will not be back-ported to 0.2.0
