### ISSUE TITLE
Betafpv AIO 20A v2

### ISSUE THREAD

**Issue by LeinesFPV** [emuflight/EmuFlight#179]
Hello, everyone,
i have the problem that my Toothpick does not work with the Betafpv AIO 20A v2.
The FC works perfectly with the MatekF411 target and Betaflight.
Unfortunately it doesn't work with EMU.

As an example: I can only arm the quad after the first time I plug in the battery. If I dissarm it then and want to arm it again, it does not work anymore.
The same applies to the OSD. I can only access it once... and then I can't access it again.

https://youtu.be/8C6Qz1FwD9o

If I want to start after the first arm, I have a fligh away...

best regards

**Comment by Kaiowarez** [comment]
This problem have been fixed, next release would have the fix

**Comment by LeinesFPV** [comment]
Many thanks for the extremely fast answer!

Do you possibly already have a working version? I would love to fly EMU on my Tooth. I have it on all 5" and I love it!

**Comment by loutwice** [comment]
i fly emu on my toothpick hx115 without problem

**Comment by gretel** [comment]
but he was asking for code, not if it is possible.
