### ISSUE TITLE
cant get smat audio 2.1 to work on helio spring 0.2.0rc unify pro nano32

### ISSUE THREAD

**Issue by anarchitstfpv** [emuflight/EmuFlight#180]
**Important: This is not the right place to get help with configuration issues. Your issue will be closed without further comment.**

Please get help from other user support options such as asking the manufacturer of the hardware you are using, RCGroups: https://rcgroups.com/forums/showthread.php?t=2464844, or Slack (registration at https://slack.betaflight.com/) or other user support forums & groups (e.g. Facebook).

**Comment by gretel** [comment]
please read your own post and try again. thank you.
