### ISSUE TITLE
Target Request for NBD HummingBird F4 1S Brushless 

### ISSUE THREAD

**Issue by Hopflnger** [emuflight/EmuFlight#203]
Hi Folks,
I wanted to request a Target for the Newbeedrone Hummingbird Board.

**Comment by Kaiowarez** [comment]
Hey, currently in the works
But can you hop on emuflight discord and send me @kaio Pryde a copy of your full dump?

**Comment by nerdCopter** [comment]
closing due: target `NBDHMBF41S` and `NBDINFINITY` exist now.  bind pin will be fixed in firmware 0.3.2

**Comment by kaio** [comment]
You mentioned the wrong username. :p

**Comment by Kaiowarez** [comment]
@kaio yes I did, lol 😂 my bad fellow kaio
