### ISSUE TITLE
Baro didnt work on SucceX F7 TwinG BT Flight Controller

### ISSUE THREAD

**Issue by Whishp** [emuflight/EmuFlight#230]
Baro didnt work on SucceX F7 TwinG BT Flight Controller https://shop.iflight-rc.com/index.php?route=product/product&product_id=930
EXF722DUAL/STM32F7X2 (S7X2)

**Comment by nerdCopter** [comment]
@Kaiowarez

**Comment by Kaiowarez** [comment]
I'll look into it, the testers versions had no baro so I prolly took it off
thinking it was not required..

**Comment by Whishp** [comment]
Mby you need some logs?

**Comment by Kaiowarez** [comment]
F7 twin g BT? Bluetooth? I never seen BT on iflight f7,
Dump helps from bf if you have em

But they have so many versions of the iff7 twin g fc one of then didn't
have a baro so I disabled it

Message me kaio Pryde in discord and I'll try to get it sorted out

**Comment by Whishp** [comment]
I can't message you in discord. Add me Whishp#6055

**Comment by nerdCopter** [comment]
non-BT version fixed and merged.
BT version, no tester report, so not merged.
