### ISSUE TITLE
EMUFlight 0.3.0 - Restore says backup created in a previous version and is incompatible with this version of configurator

### ISSUE THREAD

**Issue by rwseif** [emuflight/EmuFlight#231]
Configurator: 0.3.0
Firmware: EMUF 0.3.0
Target: CRAZYBEEF4FR

2020-05-18 @ 11:51:07 -- Backup file provided was generated for previous version of the configurator and is incompatible with this version of configurator. Sorry

but this backup was created in this version of configurator

**Comment by nerdCopter** [comment]
please CLI `dump all` and `diff all`
those buttons were never modified for any Emu version.

**Comment by nerdCopter** [comment]
closing. merged https://github.com/emuflight/EmuConfigurator/pull/189
