### ISSUE TITLE
EmuFlight Talon F7 Fusion Gyro Issue

### ISSUE THREAD

**Issue by nellikb** [emuflight/EmuFlight#234]
**Describe the bug**
Hi guys! I'm having an issue with Emuflight 0.3 where the gyro appears to cease functioning (no output on sensors page) and sometimes cause settings to get changed - Whilst trying to figure out how to reproduce this I've seen my motors get changed from DSHOT600 to brushed multiple times!

**To Reproduce**
I've had it happen while changing various settings (PIDS, Rates, OSD, Configuration) but it seems to be very repeatable while loading PID Profiles / Presets & setting them back to default preset with a LIPO plugged in. 

**Flight controller configuration**
For my most recent attempt at triggering this bug I loaded CLI defaults then changed to the 6inch preset then back to the default preset which resulted in the frozen gyro and the following diff:

```
# diff

# version
# EmuFlight / TALONF7FUSION (TALN) 0.3.0 May 18 2020 / 19:04:33 (001a051) MSP API: 1.47

board_name 
manufacturer_id 

# name

# resources

# mixer

# servo

# servo mix


# feature

# beeper

# beacon

# map

# serial

# led

# color

# mode_color

# aux

# adjrange

# rxrange

# vtx

# rxfail

# master
set imuf_roll_q = 8500
set imuf_pitch_q = 8500
set imuf_yaw_q = 8500
set imuf_w = 48
set imuf_sharpness = 2000
set dynamic_gyro_notch_q = 0
set dynamic_gyro_notch_min_hz = 0
set min_throttle = 1000
set use_unsynced_pwm = ON
set motor_pwm_protocol = BRUSHED
set motor_pwm_rate = 16000

# profile
profile 0

set smart_dterm_smoothing_roll = 75
set smart_dterm_smoothing_pitch = 75
set smart_dterm_smoothing_yaw = 75
set witchcraft_roll = 6
set witchcraft_pitch = 6
set witchcraft_yaw = 6
set spa_yaw_i = 75
set i_decay = 8
set emu_boost = 0
set emu_boost_yaw = 0
set emu_boost_limit = 0
set emu_boost_limit_yaw = 0
set p_pitch = 60
set i_pitch = 62
set d_pitch = 35
set p_roll = 52
set i_roll = 62
set d_roll = 35
set p_yaw = 65
set i_yaw = 60
set d_yaw = 15

# rateprofile
rateprofile 0

set tpa_rate_p = 100
set tpa_rate_i = 175
set tpa_rate_d = 85
set tpa_breakpoint = 1400
```

**Setup / Versions**
6 inch Apex
Talon F7 Fusion
Fettec 35A ESC
DJI FPV System

This quad was flying perfectly with Betaflight on Saturday & the only change since then is EmuFlight.

**Comment by nerdCopter** [comment]
fixes merged. will be in 0.3.2
