### ISSUE TITLE
RSSI sticks to channel 0 on F4S butterflight build 3.6.7

### ISSUE THREAD

**Issue by BeansFPV** [emuflight/EmuFlight#26]
In CLI and configurator, selecting any channel for RSSI always switches back to disabled/channel 0. RSSI on OSD is connected to throttle channel. Analog RSSI is turned on in the Config tab. I can see the RSSI signal on Receiver tab so it too is working.

Came from working XM+ setup on Betaflight 3.2x and 4.0 so I know it works ;) First github issue report.

**Comment by Quick-Flash** [comment]
have you tried emu 0.1.0 just to comfirm this bug?

**Comment by BeansFPV** [comment]
I have not yet but will try and report back. Buddy said he preferred this build's flight characteristics so I didn't bother upgrading to emu build yet.

**Comment by BeansFPV** [comment]
I can confirm it stays on emu 0.1.0 with the same behavior. I can see the RSSI varying on AUX 4 (8ch RSSI firmware on the XM+) but it still does not save the RSSI channel in the configurator (emuconfig) or the CLI.

**Comment by gretel** [comment]
@BeansFPV thanks for getting back to us! is the firmware file you flashed `XM+FCC170313-RSSI8.frk` ?

**Comment by BeansFPV** [comment]
@gretel Yes, I checked on the Taranis SD card to be sure. That's the one.

**Comment by nerdCopter** [comment]
does this help? https://youtu.be/x-qdaVpmn5o
