### ISSUE TITLE
Flywoo F405 Video doesn't work

### ISSUE THREAD

**Issue by DonkFPV** [emuflight/EmuFlight#276]
Hello,
I have a trouble with a flywoo f405 :
With 0.3 and 0.1, in the goggle I only have my osd with a light grey background. My set up work well with an other firmware (the yellow one) and I have try to passe from one to another to verify it was not the wire,the camera, the vtx or anything else and it was not. 
Please help, I don’t want to go back to the yellow firmware.

**Comment by nerdCopter** [comment]
@Kaiowarez could this possibly be an FC target issue, or does it seem non-Emu?

**Comment by DonkFPV** [comment]
I find the target in emu and all the other paramters work fine .

**Comment by Kaiowarez** [comment]
Could be target I think
I'll double check when I get home
No video maybe wrong spi.. Or resource

**Comment by DonkFPV** [comment]
@Kaiowarez please let me know when you have check? :)

**Comment by Kaiowarez** [comment]
From what I can tell flywoof405 original target is intact, can you link me
your fc.. If it's a new fc it might have changed.. And if you can drop me a
dump file from bf  I'll compare it to the current target

**Comment by Kaiowarez** [comment]
Okay thanks, looks exactly the same as the target..
Might need to assign an nss pin, if you can test it that would be great,
I'll send the hex if you can hop on discord, I try not to give the hex
targets on public since it might not work and ppl might think it works

**Comment by DonkFPV** [comment]
i don't know how assign nss pin ? is that like remaping motor ? maybee if you explain i can try.  On discord you can send the hex to donkFpv ? 
i'm not used to discord sorry

**Comment by Kaiowarez** [comment]
Okay yeah I gotta assign an nss pin.. That's internally assigned on a
target :)

**Comment by nerdCopter** [comment]
@DonkFPV we could be wrong, but we've come to the consensus that if you get OSD over a gray image, then you camera video is not feeding into FC.  we know that the FC is feeding video, otherwise you would not see OSD.   This of course assumes you are analog and not DJI.

**Comment by DonkFPV** [comment]
@nerdCopter  kaio has fixed the problem it was a pinio setting ... 
thanks to all :)

**Comment by nerdCopter** [comment]
@Kaiowarez , was this fixed with #296 ?

**Comment by Kaiowarez** [comment]
Yes all done @nerdCopter
