### ISSUE TITLE
DShot1200 0.3.1 vs 0.2.0

### ISSUE THREAD

**Issue by nerdCopter** [emuflight/EmuFlight#287]
**Describe the bug**
@ pierre meunier: "with Dshot1200 make esc buggy on 0.3.1 but work perfect on 0.2.0"
(feedback from other pilots)
paraphrasing conversation: two motors work of 4; multiple beeps, continuous beeps.

**To Reproduce**
unknown

**Flight controller configuration**
unknown, no diff or info provided

**Setup / Versions**
unknown

**Additional context**
unknown

**Comment by gretel** [comment]
even `dshot2400` fine for me, maybe monsieur meunier fried his gear or sth.

**Comment by nerdCopter** [comment]
* closing this. no feedback or other reports from proper channels.
* could have been FC specific.
