### ISSUE TITLE
[solved] No Emuflight firmware for the Transtec Beetle transtecf411hd Board

### ISSUE THREAD

**Issue by f3fphil** [emuflight/EmuFlight#288]
Would Love to fly Emuflight on my Beetle but there is not the Right Firmware the STM32F411 Says Nogyro ....

**Comment by Kaiowarez** [comment]
Noo don't assign to me @nerdCopter lol

Anyway
Post a link to the fc and a dump thanks

**Comment by f3fphil** [comment]
https://www.transtechobby.com/products/transtec-f411-hd-for-dji-fpv-system

**Comment by f3fphil** [comment]
What do i habe to copy for the Dumb ?
Thx for your help

**Comment by Kaiowarez** [comment]
Connect the fc to bf configurator
Go to cli last tab type dump
Then on lower right of the window you'd see a button save to file save to
file name it whatever you want and attach file here or post on target
request in discord works as well

Thanks

**Comment by f3fphil** [comment]
Ok thx a lot i Send it at Monday

**Comment by Kaiowarez** [comment]
No problem

**Comment by f3fphil** [comment]
[BTFL_cli_TransTEC_20200621_203827.txt](https://github.com/emuflight/EmuFlight/files/4810057/BTFL_cli_TransTEC_20200621_203827.txt)

**Comment by f3fphil** [comment]
theres the Dumb

**Comment by Kaiowarez** [comment]
hello can you join emu discord for testing?  https://discord.gg/vVtVKP3

**Comment by f3fphil** [comment]
I m on discord 
Username F3fphil

**Comment by f3fphil** [comment]
Im sorry but i dont no what i have to Search for on Discord 🙈

**Comment by nerdCopter** [comment]
@f3fphil , did you ever receive the `transtecf411hd` `.hex` ?

**Comment by MorenoMdz** [comment]
Hey, do we need testing for this still? I just got this model and wanted to give emuflight a try for indoor flying

**Comment by Kaiowarez** [comment]
Hop on discord maybe someone got it available but it's fully tested

**Comment by nerdCopter** [comment]
https://github.com/emuflight/EmuFlight/issues/288
https://github.com/emuflight/EmuFlight/pull/318
https://github.com/emuflight/EmuFlight/pull/365
