### ISSUE TITLE
Matek 5.8G VTX-MINI cli config problem

### ISSUE THREAD

**Issue by DarkSoulRL** [emuflight/EmuFlight#301]
EmuFlight / MAMBAF722 (MBF7) 0.3.1 Jun 27 2020 / 22:21:57 (0c240c226) MSP API: 1.48

This VTX has 5 power levels, but only 4 can be set in the CLI. It is configured normally through the OSD.

![image](https://user-images.githubusercontent.com/21101416/85986835-df279880-b9fd-11ea-8b5b-092ee1ccd96b.png)

![image](https://user-images.githubusercontent.com/21101416/85987082-388fc780-b9fe-11ea-8b25-9da6b3451e80.png)

**Comment by nerdCopter** [comment]
0 is a level, should be 25mw
0,1,2,3,4 = 5 levels.
now if it's really 6 levels, with 5 being the last, then maybe @Quick-Flash can fix it.
or if it's not, then the code need to be fixed to not allow `5`.

**Comment by DarkSoulRL** [comment]
Default Value 1 
In fact, 1 = 25 mW, which means 0, I do not know, I have never used it.

**Comment by nerdCopter** [comment]
@DarkSoulRL , Thank you.

@Kaiowarez , care to revisit this issue? :P -- is this target specific?
 or do we need to modify common code @Quick-Flash ?

i see the following definitions in  `src/main/drivers/vtx_common.h`: smartaudio goes to 4 and tramp goes to 5. unsure why he cannot get 5 -- i don't have Tramp to test.
```
// SmartAudio "---", 25, 200, 500, 800 mW
#define VTX_SA_POWER_OFF          0
#define VTX_SA_POWER_25           1
#define VTX_SA_POWER_200          2
#define VTX_SA_POWER_500          3
#define VTX_SA_POWER_800          4

// Tramp "---", 25, 100, 200, 400, 600 mW
#define VTX_TRAMP_POWER_OFF       0
#define VTX_TRAMP_POWER_25        1
#define VTX_TRAMP_POWER_100       2
#define VTX_TRAMP_POWER_200       3
#define VTX_TRAMP_POWER_400       4
#define VTX_TRAMP_POWER_600       5
```
are we just out-dated and there is an easy fix? or is this the whole vtx tables can-of-worms?

i see: 
`src/main/interface/settings.c:1050:    { "vtx_power",                  VAR_UINT8  | MASTER_VALUE, .config.minmax = { VTX_SETTINGS_MIN_POWER, VTX_SETTINGS_POWER_COUNT-1 }, PG_VTX_SETTINGS_CONFIG, offsetof(vtxSettingsConfig_t, power) },` so it obviously calcs the max.

**Comment by Kaiowarez** [comment]
I checked the code as well looks right logically
It might be a port setting issue not change the vtx config probably.. 
And I been soo busy that I get lucky to have time to finish half a target :(

**Comment by DarkSoulRL** [comment]
![image](https://user-images.githubusercontent.com/21101416/86099080-0c407d80-bac8-11ea-931c-6e6eb194cf39.png)
cant set 800mw  in CLI

**Comment by gretel** [comment]
`tbs` defines it's standard using 5 levels of power, while `immersionrc` defines 6 levels of power. it's all fine.
but, the vendors do not stick to these proprietary standards and do whatever they feel is fine.

the actual power levels of this particular vtx are

```
PIT, 25, 200, 400, 800mW
```

as described at http://www.mateksys.com/?portfolio=vtx-mini#tab-id-2

**Comment by nerdCopter** [comment]
#705
