### ISSUE TITLE
gps speed

### ISSUE THREAD

**Issue by loopingfpv** [emuflight/EmuFlight#317]
salut,
je suis devant un fait assez désagréable, en installant mon module gps avec emuflight et en activant la le gps speed, la vitesse est en cm/sec serait il possible de modifier pour indiquer la vitesse en km/h. Aussi, dans l'onglet osd il manque la case flip arrow comme dans betaflight
merci

**Comment by loopingfpv** [comment]
salut, 
je suis devant un fait assez désagréable, en installant mon module gps avec emuflight et en activant la le gps speed, la vitesse est en cm/sec serait il possible de modifier pour indiquer la vitesse en km/h. Aussi, dans l'onglet osd il manque la case flip arrow comme dans betaflight
merci

**Comment by nerdCopter** [comment]
google translation: 
```
Hi,
I am faced with a rather unpleasant fact, by installing my gps module with emuflight and by activating
 the gps speed,  the speed is in cm / sec it would be possible to modify to indicate the speed in km / h. 
Also, in the tab osd it misses  the box flip arrow as in betaflight
thank you
```

@loopingfpv , I do not personally know about the `km/h`.
But i think you are needing the expert-mode in OSD:
![2020-07-11_11-29](https://user-images.githubusercontent.com/56646290/87228899-df168980-c369-11ea-89f4-800e008b87c2.png)

**Comment by loopingfpv** [comment]
Hi... I'm in expert mode. But on my osd it is in cm/secEnvoyé depuis mon téléphone Huawei-------- Message original --------De : nerdCopter <notifications@github.com>Date : sam. 11 juil. 2020 à 18:32À : emuflight/EmuFlight <EmuFlight@noreply.github.com>Cc : loopingfpv <dbutera@skynet.be>, Mention <mention@noreply.github.com>Objet : Re: [emuflight/EmuFlight] gps speed (#317)
google translation:
Hi,
I am faced with a rather unpleasant fact, by installing my gps module with emuflight and by activating
 the gps speed,  the speed is in cm / sec it would be possible to modify to indicate the speed in km / h. 
Also, in the tab osd it misses  the box flip arrow as in betaflight
thank you

@loopingfpv , I do not personally know about the km/h.
But i think you are needing the expert-mode in OSD:

**Comment by gretel** [comment]
https://github.com/emuflight/EmuFlight/blob/fb696a2482e5bb4eb4f173e8011e7d8d427f9ea2/src/main/io/osd.c#L503
