### ISSUE TITLE
[solved] Building AutoComplete Cache ... Failed! [solution: very old NW.js dependencies]

### ISSUE THREAD

**Issue by ludiga** [emuflight/EmuFlight#328]
The CLI don't work.
FC Mamba F722s. Flashed with the full chip erase mode but the cli don't work.
Tested win 64 and 32 .exe files.

thk

**Comment by nerdCopter** [comment]
* i just added some new `.exe` and `.zip` today for CLI buffer bug.  
* cehck the release assets, new files are named `..._fixed...`
* i suggest test the .zip first, less waiting on installer

**Comment by nerdCopter** [comment]
0.3.3 release page has some new files with `_fixed` in thte names.
