### ISSUE TITLE
[solved] Missing EmuFlight target for HGLRC F722

### ISSUE THREAD

**Issue by davidj802** [emuflight/EmuFlight#332]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Please note that feature requests are not 'fire and forget'. It is a lot more likely that the feature you would like to have will be implemented if you keep watching your feature request, and provide more details to developers looking into implementing your feature, and help them with testing.

**Comment by nerdCopter** [comment]
@davidj802 , are you in EmuFlight Discord? we have that target now, just not released.

**Comment by davidj802** [comment]
@nerdCopter, Thanks just found target file on Discord.
