### ISSUE TITLE
Resource remapping LED pin bricks Flywoo FC

### ISSUE THREAD

**Issue by fiveseven808** [emuflight/EmuFlight#334]
**Describe the bug**
When I remap my resource pin from the default (incorrect) pin for FLYWOOF411 target, my FC gets bricked and needs to be reflashed

**To Reproduce**
Flash emuflight FLYWOOF411 0.3.1 on Flywoo 16x16 F4 stack. 
Map via:
resource pinio 2 none
resource led_strip 1 A15

**Expected behavior**
Since these assignments are from the betaflight firmware, the LED should work and nothing else should change. 

**Flight controller configuration**
The aforementioned change is the only diff

**Comment by Kaiowarez** [comment]
So a15 is led strip and no cam control.. 🤔 I'll redo the timers
Led strip is assigned thru timers so it'll brick if you reassign it

**Comment by nerdCopter** [comment]
@fiveseven808 , are you on Discord so we can send you.hex for testing?
https://discord.gg/gdP9CwE

**Comment by nerdCopter** [comment]
* reported LEDs work.
* waiting for additional feedback make sure nothing else affected.

**Comment by nerdCopter** [comment]
* reported failure
* see https://github.com/emuflight/EmuFlight/pull/335 for details

**Comment by nerdCopter** [comment]
* fixed Aug 19 with https://github.com/emuflight/EmuFlight/pull/342
