### ISSUE TITLE
[solved] [use JHEF7DUAL] f7xsd flight controller (jhef7dual target) 

### ISSUE THREAD

**Issue by gbbulciolu** [emuflight/EmuFlight#360]
SOLVED: No gyro available, impossible to calibrate. On BF, same target (JHEF7DUAL) works as expected.
Board: F7-XSD, same as this 
![image](https://user-images.githubusercontent.com/65344478/94340972-3392e200-0006-11eb-87c5-c14a52ece85f.png)
use cli command **set gyro_to_use = second**

**Comment by nerdCopter** [comment]
@Kaiowarez 
http://jhemcu.com/e_productshow/?19-JHEMCU-Betaflight-F7-XSD-2020mm-FC-OSD-5V-9V-BEC-19.html

**Comment by nerdCopter** [comment]
@Kaiowarez , i'm pretty sure these are clones of other products, so maybe "original" targets are to be used?
`BETAFLIGHTXXX` ?

**Comment by gbbulciolu** [comment]
Probably clones, but on BF with same target has no issues and works as expected.

**Comment by Kaiowarez** [comment]
Problem is betaflight auto detects..
Try to change default gyro
Coz this fc only have 1 gyro

**Comment by gbbulciolu** [comment]
problem is on emuflight, on bf it works like a charm.

**Comment by Kaiowarez** [comment]
Get me a dump from bf and I'll see what is the issue

**Comment by sebas1984x** [comment]
I can't get the osd voltage right, when plugged in a 3s it still says 4s. I calibrated but tha doesn't help.

**Comment by nerdCopter** [comment]
@sebas1984x , there should be a better solution, but `set force_battery_cell_count = 4` might get you airborne.  I personally have no answer to why it's not working for you.

**Comment by gbbulciolu** [comment]
> info from internal discussions: `gyro is mpu ... just needs to set use gyro 2`
> i.e. BeF unified targets finds mismatched hardware and fixes internally, our targets are static and this FC is a modified clone.

thanks for the tip... the correct cli command is: set gyro_to_use = second (possible choices: both, first, second).
cheers

**Comment by majoe17** [comment]
> I can't get the osd voltage right, when plugged in a 3s it still says 4s. I calibrated but tha doesn't help.

Hello, have you solve this one?

**Comment by nerdCopter** [comment]
did cli command help? `set force_battery_cell_count = X`  @sebas1984x ? 
@Kaiowarez might have to look into it further.  are you running 0.3.2 @majoe17 ?

**Comment by sebas1984x** [comment]
Nope, can't get it right. Tried everything

**Comment by Kaiowarez** [comment]
I never modified this target I looked at it tho..  It's a legacy target I could rewrite it maybe tomorrow the earliest

**Comment by majoe17** [comment]
@nerdCopter i used all available firmware. Emu and betaflight. Still no luck. I already did that force count cell, still no luck.

**Comment by majoe17** [comment]
I plugged in a 2s lipo but the configurator says 7s. Did some calibration, 110 down to 29, then whenever i plugged in a fresh, not fresh or almost empty 2s lipo, it will show the voltage i used to calibrate.

**Comment by nerdCopter** [comment]
@majoe17 , @sebas1984x ... if even betaflight fails, then i would contact the vendor for fix, instruction, or even a replacement. maybe they have know hardware problems. 
Do you agree @Kaiowarez ?

**Comment by nerdCopter** [comment]
> Hello, has any new information about fix wrong voltage? I try last EmuFlight and BetaFlight - broblem is the same.

no news. i can only recommend calibrate, but if it fails, then i have no other solution.

https://youtu.be/ZbyuPCcXh-8

![image](https://user-images.githubusercontent.com/56646290/197807463-e2e0884d-c921-43d3-ba65-50a7ff624871.png)
