### ISSUE TITLE
[Target Request] GEPRCF411_PRO target please

### ISSUE THREAD

**Issue by Redshifft** [emuflight/EmuFlight#406]
Any Chance of getting the GEPRCF411_PRO target added please?

This is the BF code link .. https://github.com/betaflight/unified-targets/commit/b52339c5c656b63d70409ce2e8a1fdeae8d90985

Thanks

**Comment by nerdCopter** [comment]
closed by #425 .

**Comment by Redshifft** [comment]
Thanks Guys  :)
