### ISSUE TITLE
OSD not showing all options

### ISSUE THREAD

**Issue by thommicom** [emuflight/EmuFlight#412]
Not all options are visible in the Emuflight configurator. E.g. I miss any kind of GPS item and other items.

To get around the problem, I can select the options I want to see via the transmitted image of the VTX. These then appear in the middle of the screen. Now I can use the Emuflight configurator to move the item to where I want it. The item is still not displayed in the selection list in the Configurator, but is still shown in the preview.

I have the problem on different flight controllers. The problem also occurs on a second computer. Reinstallation of EMuflight on the flight controller and reinstallation of the configurator were unfortunately unsuccessful.

<img width="1680" alt="Bildschirmfoto 2020-11-19 um 10 57 23" src="https://user-images.githubusercontent.com/74709379/99650803-261e3500-2a56-11eb-8809-b92a1dcc153d.png">

**Comment by Zlopi** [comment]
![image](https://user-images.githubusercontent.com/13034887/99656078-87053780-2a6d-11eb-9331-148349faccc8.png)

Try this enable its? you should very like it... =)))

**Comment by Zlopi** [comment]
![image](https://user-images.githubusercontent.com/13034887/99657303-0e9f7600-2a6f-11eb-94d0-c8f45eb0f0e0.png)

Maybe turn on GPS first?

**Comment by thommicom** [comment]
F**k. Thats it. In Expert Mode the missing Items are visible. GPS was already turned on before. 

Thanks a million!
