### ISSUE TITLE
jittering cycle time when TELEMETRY is turned on.

### ISSUE THREAD

**Issue by gretel** [emuflight/EmuFlight#42]
**Describe the bug**
cycle times (shown in the configurator) jumping from 120 to 1020 every second or so.

**To Reproduce**
enable TELEMETRY feature, watch the cycle time.

**Expected behavior**
constant cycle time.

**Setup / Versions**
2x MATEKF411RX, FURY4OSD, OMNIBUSF4

**Comment by gretel** [comment]
![image](https://user-images.githubusercontent.com/80815/68088065-919d6080-fe5b-11e9-8fed-a543557a896a.png)

@bubi-007 do you think this might be related? i don't have the skillset required to figure this out..

**Comment by bubi-007** [comment]
i haven't played with telemetry a lot.
i just don't use it at the moment.
but yes - it is a candidate.
another one is known to create jitter on the time axis: led

**Comment by gretel** [comment]
@bubi-007 thanks, are there any best practices..tools you know of which might help debugging this?

**Comment by bubi-007** [comment]
measuring code exection time by hand i assume.
and then log it manually: debug[0] = deltaTimeInMs * 1000 for example.
the same for jitter in the calling frequency.

**Comment by gretel** [comment]
@bubi-007 feel like `jlink` debugging would be helpful to get some measurements during runtime. 

https://github.com/Serj-Bashlayev/STM32_Profiler

**Comment by bubi-007** [comment]
looks good to me.
haven't used this.
so ahead and report back.
but i don't think the resulting binary would be flyable due to the overhead.

**Comment by gretel** [comment]
@bubi-007 ya it's getting crowded in the flash space... running out of options.

**Comment by gretel** [comment]
https://wiki.st.com/stm32mpu/wiki/Valgrind

**Comment by bubi-007** [comment]
stm32mpu !?!?
wrong film.
but very interesting platform :-)
would love it to have one!

**Comment by gretel** [comment]
ah ya me stoopid.

**Comment by bubi-007** [comment]
no, it is the future.

**Comment by gretel** [comment]
the not-so-far-future is fixing this bug :)

**Comment by adrianmiriuta** [comment]
@gretel 

this is the culprit.
comment out gyroReadTemperature();
it's not used anyway ...


#ifdef USE_TELEMETRY
void subTaskTelemetryPollSensors(timeUs_t currentTimeUs)
{
    UNUSED(currentTimeUs);

    // Read out gyro temperature if used for telemmetry
    gyroReadTemperature();
}
#endif

**Comment by gretel** [comment]
@adrianmiriuta did a pull request.. thanks! how did you figure?

**Comment by Quick-Flash** [comment]
@adrianmiriuta I would really like to get into contact with you. Any chance that I can do that?

**Comment by adrianmiriuta** [comment]
@gretel 
Has the same problem with my branch 6 months ago.
@Quick-Flash 
See Discord message
