### ISSUE TITLE
Add Redpine Radio Protocol

### ISSUE THREAD

**Issue by BrickSolid28** [emuflight/EmuFlight#420]
Redpine protocol is a ultra low speed radio protocol.  It has been implemented into Betaflight and I'd love to see it added as an option in the Emuflight configurator.

http://www.multirotorguide.com/guide/redpine-the-fastest-radio-control-protocol/

**Comment by nerdCopter** [comment]
https://github.com/emuflight/EmuFlight/pull/444

**Comment by bengmo64** [comment]
Yes please, if anyone could do this I would be excited to be able to fly low latency instead of the ancient d8 mode

**Comment by iz3man** [comment]
Me too. Please add if possible!!!

**Comment by Quick-Flash** [comment]
trying, its tricky.

**Comment by nerdCopter** [comment]
#654 
#699
