### ISSUE TITLE
[Target Request]  MAMBAF722_I2C 

### ISSUE THREAD

**Issue by spar444** [emuflight/EmuFlight#428]

**Comment by nerdCopter** [comment]
please send cli `dump` from betaflight or link to unified target.
please send link to official product specs.

**Comment by spar444** [comment]
Targer - https://cdn.shopify.com/s/files/1/0027/2708/4144/files/MAMBA_F722_I2C_0716.config?v=1603377151
Dump - https://drive.google.com/file/d/1kT04KVcL_HGbSeHp_CqFxXto2mldSXOk/view?usp=sharing
Link to official store - https://www.diatone.us/collections/flightcontroller/products/mamba-f722s-flight-controller

**Comment by nerdCopter** [comment]
@spar444 would you like to join Discord and @nerdCopter or "@Kaio Pryde" to test the target?

**Comment by spar444** [comment]
I'm already there:)

**Comment by nerdCopter** [comment]
closed by https://github.com/emuflight/EmuFlight/pull/474
