### ISSUE TITLE
battery voltage shown as '0.0V' when using HV packs

### ISSUE THREAD

**Issue by gretel** [emuflight/EmuFlight#43]
**Describe the bug**
OSD shows voltage of 0.0V when connecting fully charged packs.

**To Reproduce**
connect a HV pack and watch the OSD.

**Expected behavior**
battery voltage should be shown correct.

**Flight controller configuration**
workaround is to adjust "max cell voltage" to 4.5V which leads to another issue: the battery meter won't show the correct relations.

**Setup / Versions**
2x MATEKF411RX, FURY4OSD

**Comment by Quick-Flash** [comment]
Give 0.1.21 a try. Updates to the battery and adding the motor output limit are included in here. Probably fixes any issues you have.

**Comment by gretel** [comment]
testers were reporting it's even "more broken" now, so i am not going to risk it for a probabilty.

**Comment by gretel** [comment]
fix is included in upcoming release.. closing for now.
