### ISSUE TITLE
flyaway on the default PIDs when running micros (2.5")

### ISSUE THREAD

**Issue by gretel** [emuflight/EmuFlight#44]
**Describe the bug**
quad skyrockets.

**To Reproduce**
build a micro, keep the default PIDs, arm, dip throttle.

**Expected behavior**
default PIDs should not be dangerous.
"workaround" is to set all PID to half of the defaults values and tune from there.
`I` seems to be the most critical one.

**Setup / Versions**
FURY4OSD

**Comment by Quick-Flash** [comment]
Wouldn't call this a bug. Just means that default tunes dont work for every craft. Try test build 0.1.20 and see if it helps at all.

**Comment by bubi-007** [comment]
a bad tune would cause a flip over of the kwad or it would behave very sluggish in the air.
when it goes straight then it is leveling perfectly and the mixer does it's job as well.
a log would help - as i think it is a windup problem.
too many boosting options.

**Comment by gretel** [comment]
@bubi-007 i was suspecting a windup, too - did turn `emuboost` and `throttle boost` off - just the bare minimum was set. i forgot to turn the blackbox on, and will have rain for some time - going to get back when i get to log.

**Comment by bubi-007** [comment]
emuboost doesn't cause a windup - throttle as well.
in my case it was an itermboost.
clearly visible in the log file.
that bug pop's up frequently - and thus it should be loggable.

**Comment by gretel** [comment]
@bubi-007 not sure what `itermboost` - `TPA` for `I` is below 1 in my case.

**Comment by bubi-007** [comment]
airmode

**Comment by gretel** [comment]
@bubi-007 are you saying i should try again with `airmode` off?

**Comment by bubi-007** [comment]
yes

**Comment by gretel** [comment]
https://wiki.st.com/stm32mpu/wiki/Valgrind

**Comment by Quick-Flash** [comment]
is this fixed in 0.2.0?

**Comment by gretel** [comment]
@Quick-Flash ya

**Comment by Quick-Flash** [comment]
brilliant than this issue is fixed!
