### ISSUE TITLE
no osd data

### ISSUE THREAD

**Issue by sotosstylic** [emuflight/EmuFlight#447]
i have no osd data to target  betafpvf405 
i can see voltages to 0.00 and time stays at 0

**Comment by nerdCopter** [comment]
@Kaiowarez , is this config issue or target issue?

**Comment by sotosstylic** [comment]
set battery_meter = ADC 
That fixed my problem
But when i arm osd data getting faded.maybe a solution for this ?? Thank you !!

**Comment by nerdCopter** [comment]
i do not understand what you describe.  maybe a solder issue? voltage regulator issue? i dont know :(
jump on discord for "support", maybe someone can help, may need to provide photos if that manageable.
https://discord.gg/gdP9CwE
