### ISSUE TITLE
included documentation is incomplete, outdated, not reflecting the actual code

### ISSUE THREAD

**Issue by gretel** [emuflight/EmuFlight#45]
**Describe the solution you'd like**
documentation should be actual and complete.

**Comment by Quick-Flash** [comment]
I think that documentation in the wiki might be the best way to go about this. That way we can get the wiki to be nice and organized as well as getting our overall documentation up to speed.

**Comment by gretel** [comment]
i was referring to the documentation being included in the repository now, which should eventually be removed.
