### ISSUE TITLE
Setting up target DFRF722 the default settings include an enabled magnetometer and barometer. One of which is not supported by default and the other not supported if uart 3 is used.

### ISSUE THREAD

**Issue by PegasusFPV** [emuflight/EmuFlight#469]
When setting up a new flight controller (the Dfr f7 dual) with the target DFRF722, the magnetometer and barometer are turned on by default. However these are not supported by the FC and thus it displays the load error in the osd an refuses to start a flight. It would be better off with them disabled by default as it would enable the quadcopter to function normally in the first place, and if hooked up they can be enabled by the user. Cheers, and emu is boss

**Comment by Kaiowarez** [comment]
Should I turn them off by default?

**Comment by PegasusFPV** [comment]
Yes that would fix the issue for new pilots, and whoever wants to use a baro or magnetometer can turn it on.

**Comment by Kaiowarez** [comment]
Ok cools will do that thanks for the advice

**Comment by nerdCopter** [comment]
@Kaiowarez , would this modification fix both baro+mag or just baro (or neither?)
```diff
-#define SENSORS_SET             (SENSOR_ACC | SENSOR_BARO)
+#define SENSORS_SET             (SENSOR_ACC)
```
