### ISSUE TITLE
[Target Request] Kakute F7 Mini v3

### ISSUE THREAD

**Issue by Xedos9er** [emuflight/EmuFlight#476]
**Vendor/Model**
Please provide the target name. e.g. `KAKUTEF7MINIV3`
Please provide vendor and model of the FC. e.g. `Kakute F7 Mini v3`
Please provide a lint to the vendor specifications : http://www.holybro.com/product/kakute-f7-mini-v3/

**CLI dump or Unified Target**
Please provide a CLI `dump` or link to unified target.
https://github.com/betaflight/unified-targets/blob/master/configs/default/HBRO-KAKUTEF7MINIV3.config

**Comment by BeauBrewski** [comment]
Needs tested
https://discord.com/channels/547211754845765635/691022009865338950/787385647870378014

**Comment by BeauBrewski** [comment]
Can close, is on the official release list with 0.3.4
