### ISSUE TITLE
[Solved] Add Arm status via Telemetry [PR exists]

### ISSUE THREAD

**Issue by Xedos9er** [emuflight/EmuFlight#481]
**Is your feature request related to a problem? Please describe.**
In EMUflight you get no information about Arm status via Telemetry. Some lua scripts will not work, because they need arm status.

**Describe the solution you'd like**
Use same method as BF for arm status. Just add a " * " to flight mode when not armed.
Example:
ACRO* -> not armed
ACRO -> armed

**Describe alternatives you've considered**
no alternative, most scripts are meant to work with BF or INAV

**Comment by Xedos9er** [comment]
Is there anyone who can implement this feature? Basically it can be copied 1:1 from Betaflight.

**Comment by nerdCopter** [comment]
can you point to the BF Pull-Reqeust or "all" the code involved?

**Comment by Xedos9er** [comment]
Since I'm not a coding guy, I can't tell you where you can find the part of the code involved into this.

**Comment by Xedos9er** [comment]
@nerdCopter 
Tim Eckel created a pull request with all needed information:
https://github.com/emuflight/EmuFlight/pull/506

**Comment by nerdCopter** [comment]
@Xedos9er what target FC's may i provide your your testing of # 506?

**Comment by Xedos9er** [comment]
@nerdCopter 
of course i can test. Target HGLRCF722

**Comment by nerdCopter** [comment]
[EmuFlight_0.3.3_HGLRCF722_Build_1385_4f23626d4.hex.zip](https://github.com/emuflight/EmuFlight/files/6055170/EmuFlight_0.3.3_HGLRCF722_Build_1385_4f23626d4.hex.zip)

**Comment by Xedos9er** [comment]
@nerdCopter 
It´s working! Please implement into next version.

**Comment by Quick-Flash** [comment]
this has been solved closing.
