### ISSUE TITLE
[Target Request] BETAFPVF411RX Betafpv 1S AIO

### ISSUE THREAD

**Issue by dsrezoon** [emuflight/EmuFlight#486]
**Vendor/Model**

BETAFPVF411RX
BETAFPV F4 1S AIO Brushless Flight Controller

https://betafpv.com/products/f4-1s-aio-brushless-flight-controller

**CLI dump or Unified Target**
https://github.com/betaflight/unified-targets/tree/master/configs/default/BEFH-BETAFPVF411RX.config

**Comment by BeauBrewski** [comment]
Seen where people on the Discord and FB page have used MatekF411Rx for this board with good results.

**Comment by BeauBrewski** [comment]
Also seeing one case where unable to bind one of these boards with the PNP SPI receiver using MatekF411Rx

**Comment by andreyk72** [comment]
No RX version of the board:
Gyro - OK, needed to calibrate accelerometer, by default it was like for "upside down" configuration. 
Accelerometer - OK, fly in angle mode no problem
Serial port 1 - OK (ELRS receiver)
Motors - OK
VTX control over Softserial port - OK
SPI RX (external via connector) - Didn't tested, do not use one
LEDS - not tested yet

**Comment by BeauBrewski** [comment]
@andreyk72 awesome, thanks for testing and pointing out the alignment! The BetaFlight config has it as CW180, which is what I have it set at. The BetaFPV Meteor75 CLI from their website has it as CW0FLIP. So I think I should use that setting instead.

**Comment by BeauBrewski** [comment]
@andreyk72 I made the change to the orientation and updated the file above *if* you want to recheck it. Thank you!

**Comment by SKREAMfpv** [comment]
I can confirm that the BETAFPVF411RX target works with the external SPI receiver.

Thank you for working on this and getting it out @BeauBrewski!

**Comment by BeauBrewski** [comment]
> I can confirm that the BETAFPVF411RX target works with the external SPI receiver.
> 
@SKREAMfpv That is *OUTSTANDING* news! Thank you for the feedback on that! Everything else good? Any noticeable issues?

**Comment by SKREAMfpv** [comment]
@BeauBrewski Haven't experienced any issues with it yet! I was able to bind and LOS with this target in a babytooth setup in my living room. When the weather clears up I will maiden 'er FPV and report back!

**Comment by nerdCopter** [comment]
> @andreyk72 awesome, thanks for testing and pointing out the alignment! The BetaFlight config has it as CW180, which is what I have it set at. The BetaFPV Meteor75 CLI from their website has it as CW0FLIP. So I think I should use that setting instead.

usually flightware should keep it at hardware's default, and if a vendor creates a quad that aligns it differently, such is not to be set as hardware default, but instead part of the pilot/model configuration.

**Comment by Olafaloofian** [comment]
I have no OSD on my BetaFPV F4 AIO using this firmware

**Comment by nerdCopter** [comment]
> I have no OSD on my BetaFPV F4 AIO using this firmware

even with OSD enabled?
![image](https://user-images.githubusercontent.com/56646290/149348859-7be1e287-6bea-4cbe-bcc6-b7297b1f9e1c.png)
or
```
feature OSD
save
```

**Comment by BeauBrewski** [comment]
Target merged to master. CLosing

**Comment by tnttim1973** [comment]
> Seen where people on the Discord and FB page have used MatekF411Rx for this board with good results.

This fixed my issue. 

 I have the [F4 Brushed Flight Controller (SPI FUTABA RX + OSD)](https://betafpv.com/collections/brushed-flight-controller/products/f4-brushed-flight-controller-spi-futaba-rx-osd) . 

![2022-03-13_011628](https://user-images.githubusercontent.com/101493755/158047924-59303978-968c-4b94-a5bd-b3490ecad8c1.jpg)

 When I updated to the latest firmware (BETAFPVF411RX 4.2.11) I lost communication to the receiver chips and the red LED would no longer light up. Only the Green LED stayed on constant. The bind button did nothing.  I tried older versions and still nothing. Right before I was about to throw it away, I seen this recommendation in the Matek version. In the software it does say that this is the chipset being used. 

 I tried the MATEKF411RX and as soon as it was completed the red LED came on and it was able to bind to my Futaba T8J. 

![2022-03-13_012757](https://user-images.githubusercontent.com/101493755/158047974-c5b60dde-2056-4c59-9f8e-6b6d8a8827d4.jpg)

![2022-03-13_012536](https://user-images.githubusercontent.com/101493755/158048022-101d8f84-2e94-48e6-a66b-4ccf7dfa67d1.jpg)

![2022-03-13_012601](https://user-images.githubusercontent.com/101493755/158048025-04cfe437-6950-48db-a19a-3b965c9a4163.jpg)

Here is the CLI Dump in Text. 

[BTFL_cli_20220313_013132.txt](https://github.com/emuflight/EmuFlight/files/8239071/BTFL_cli_20220313_013132.txt)

Hope this helps someone, I think this will be the last BetaFPV items I buy from them as they have very little to any support for their stuff. 
Tim

**Comment by BeauBrewski** [comment]
@tnttim1973 
Betafpv support is a nightmare and confusing as heck. Just want to point out that on the link you sent, it does list `MATEKF411RX` as the firmware, as well as at the beginning of your BF dump.
![image](https://user-images.githubusercontent.com/85623381/158059128-e4972997-3597-49be-bec8-fd3a7674e05c.png)

And for future reference to make life easy, before flashing or upgrading, always check what target version came installed. It will be listed at the top left and bottom right of the configurator:
![image](https://user-images.githubusercontent.com/85623381/158059444-df8dc3cd-ef8a-4f65-ac40-bca6a9853161.png)

Or you can go into CLI and type `version`
![image](https://user-images.githubusercontent.com/85623381/158059522-e9cff7cf-c359-4c7b-9153-7ac00d3b1aa7.png)

Lastly, before pulling your hair out or tossing your FC in the trash, you can always ask on the Emuflight facebook page, discord, or on Github, and one of us will help you figure it out 😄 

Glad you got it figured out!
