### ISSUE TITLE
[Target Request] TMOTORF411 AIO

### ISSUE THREAD

**Issue by tom-bossa** [emuflight/EmuFlight#487]
Target name : TMOTORF411

New T-Motor 13A F4 AIO that can be found in the Tron 80 Digital Whoop here : 
https://store-en.tmotor.com/goods.php?id=1136

Unified Target :
https://github.com/betaflight/unified-targets/blob/master/configs/default/TMTR-TMOTORF411.config

❤🐥

**Comment by tricade1** [comment]
@tom-bossa Can I use the target TMOTORF4 for the Tron 80HD ? Or do I have to wait until you added TMOTORF411? As I do have the Tron here and would love to test it!

**Comment by nerdCopter** [comment]
i would have to assume that `F4` and `F411` are too different and would not work.

**Comment by tricade1** [comment]
So the short info is - wait until you added it in emuflight :) correct ? Can’t wait !

**Comment by tricade1** [comment]
I can see that in v0.4 STM32F411DISCOVERY has been added .... can I use this for the TRON? as its a STM32F411

**Comment by nerdCopter** [comment]
> I can see that in v0.4 STM32F411DISCOVERY has been added .... can I use this for the TRON? as its a STM32F411

Please do not use the `STM*.hex` files at all, they are not real targets.  Emu is not unified targets.

**Comment by BeauBrewski** [comment]
Needs tested!
Check gyro orientation, motor arrangement, flash, osd, vtx control, everything else if possible please update here
PROPS OFF FOR SAFETY

[EmuFlight_0.4.0_TMTR_TMOTORF411_Build_3cfba270f.zip](https://github.com/emuflight/EmuFlight/files/7538427/EmuFlight_0.4.0_TMTR_TMOTORF411_Build_3cfba270f.zip)

**Comment by tricade1** [comment]
very nice - does anybody has a good tune for EMU?

**Comment by nerdCopter** [comment]
> very nice - does anybody has a good tune for EMU?

Every quad is different. need to tune or get "close" with the presets in the EmuConfigurator.  Join the EmuFlight Discord for help, Github is for development efforts and issue tracking.

**Comment by BeauBrewski** [comment]
@tricade1 @tom-bossa 
Any feedback on this test target?
Any updates of functionality of this target?
✔️/❌ Flash
✔️/❌ Gyro
✔️/❌ Accelerometer
✔️/❌ Motors
✔️/❌ Onboard ADC
✔️/❌ OSD (analog)
✔️/❌ Smart Audio controls (OSD and CLI)
✔️/❌ Alarm switch
✔️/❌ Barometer
✔️/❌ Blackbox
✔️/❌ LED
✔️/❌ GPS
Or any other features, issues you noticed?
