### ISSUE TITLE
[Target Request] FLYWOOF745

### ISSUE THREAD

**Issue by Julianus43** [emuflight/EmuFlight#495]
**Vendor/Model**
Target Name: FLYWOOF745
Vendor and Modell: Flywoo GOKU HD 745 EVO 40A AIO BL_32 and other F7 FCs
[https://flywoo.net/collections/goku-evo-aio/products/goku-hd745-evo-40a-aio-bl_32-dji-plus-play](url)

**CLI dump or Unified Target**
https://github.com/betaflight/unified-targets/blob/master/configs/default/FLWO-FLYWOOF745.config

**Comment by Roccccky** [comment]
Also following. I have GOKU GN F4 40A AIO and when i remap all resources from working bf 4.2.6 it bricks my fc.

**Comment by kimxilxyong** [comment]
Me too would like to have the FLYWOOF745  (Flywoo GOKU GN745 2-6S AIO)

**Comment by BeauBrewski** [comment]
Targets been merged. Closing.
