### ISSUE TITLE
Tmotor F4 target

### ISSUE THREAD

**Issue by GhostMaster9** [emuflight/EmuFlight#50]
Hi, can you please add a Tmotor F4 target? 

This is the unified target config used in betaflight, this should help.

https://github.com/betaflight/unified-targets/blob/master/configs/default/TMTR-TMOTORF4.config

Thank you very much.

**Comment by gretel** [comment]
@GhostMaster9 as we currently have a different infrastructure than bf we can not just copy their `cfg` files over.

support got added but is untested and not scheduled for release for now.

**Comment by GhostMaster9** [comment]
can i test the target please? thanks

**Comment by gretel** [comment]
@GhostMaster9 ok, but we will not be able to fix issues you might have using it. please take the props off! [EmuFlight_0.1.21_TMOTORF4.hex.zip](https://github.com/emuflight/EmuFlight/files/3806964/EmuFlight_0.1.21_TMOTORF4.hex.zip)

**Comment by GhostMaster9** [comment]
> @GhostMaster9 ok, but we will not be able to fix issues you might have using it. please take the props off! [EmuFlight_0.1.21_TMOTORF4.hex.zip](https://github.com/emuflight/EmuFlight/files/3806964/EmuFlight_0.1.21_TMOTORF4.hex.zip)

thank you so much, it's working perfectly. smooth as expected from emuflight. :D

**Comment by gretel** [comment]
@GhostMaster9 @emuflight/emuteam cool, thanks for the feedback. will be included in the next release!
