### ISSUE TITLE
Target Request - PODRACERAIO

### ISSUE THREAD

**Issue by Mcrubens** [emuflight/EmuFlight#507]
**Vendor/Model**
PODRACERAIO (PODRACERAIO)
board_name PODRACERAIO
manufacturer_id TEBS

**CLI dump or Unified Target**
see attachment
[Dump PODRACERAIO.txt](https://github.com/emuflight/EmuFlight/files/6055308/Dump.PODRACERAIO.txt)

**Comment by madchiller** [comment]
Im on this...  Working with Mike Chin and TBS on it...

**Comment by madchiller** [comment]
First Test version made and tested by Mike Chin...   Replied to Mcrubens with Test Target in Discord to try.  #target-request-and-testing.

**Comment by BeauBrewski** [comment]
Can close, I think. There's an official 0.3.4 release listed?
