### ISSUE TITLE
[Target Request] HGLRC Zeus25 AIO 3-6S F722

### ISSUE THREAD

**Issue by r7972963** [emuflight/EmuFlight#525]
**Vendor/Model**
HGLRC Zeus25 AIO 3-6S F722 Flight Controller 25A BL32 4in1 ESC
https://www.hglrc.com/products/hglrc-zeus25-aio-3-6s-f722-flight-controller-25a-bl32-4in1-esc

**CLI dump or Unified Target**
https://github.com/betaflight/unified-targets/blob/master/configs/default/HGLR-ZEUSF722_AIO.config

**Comment by aepkolol** [comment]
Came here to request this FC as well.

**Comment by adracea** [comment]
Would also like to request this target.

**Comment by nerdCopter** [comment]
@Kaiowarez , is this "`HGLR_HGLRCF722`" ??

**Comment by nerdCopter** [comment]
[EmuFlight_0.3.4_HGLR_HGLRCF722_Build_1330fb967.hex.zip](https://github.com/emuflight/EmuFlight/files/6743087/EmuFlight_0.3.4_HGLR_HGLRCF722_Build_1330fb967.hex.zip)

please test and feedback, TY!

**Comment by adracea** [comment]
> @Kaiowarez , is this "`HGLR_HGLRCF722`" ??

The only difference in the configs seems to be the ZEUS25 also having these lines changed, I'm not sure how this affects things though.  
```
set gyro_1_sensor_align = CW180FLIP
set gyro_1_align_pitch = 1800
```

**Comment by Kaiowarez** [comment]
Might just need a sub branch to make those changes

**Comment by BeauBrewski** [comment]
> @Kaiowarez , is this "`HGLR_HGLRCF722`" ??

Should be HGLR-ZEUSF722_AIO according to manufacturer website and BF config.

**Comment by BeauBrewski** [comment]
Needs tested!
Check gyro orientation, motor arrangement, flash, vtx control, everything else if possible please update here
PROPS OFF FOR SAFETY

[EmuFlight_0.4.0_HGLR-ZEUSF722_AIO_Build_4b10ba7ba.zip](https://github.com/emuflight/EmuFlight/files/7534145/EmuFlight_0.4.0_HGLR-ZEUSF722_AIO_Build_4b10ba7ba.zip)

**Comment by nerdCopter** [comment]
@BeauBrewski please rename your target without hyphen. use underscore only, ty.

**Comment by RustyRobotbits** [comment]
First flight was successful. Used this .hex for my Zeus35 pro aio fc. Will continue to test.

**Comment by BeauBrewski** [comment]
@RustyRobotbits 
Any feedback is much appreciated!
✔️/❌ Flash
✔️/❌ Gyro
✔️/❌ Accelerometer
✔️/❌ Motors
✔️/❌ Onboard ADC
✔️/❌ OSD (analog)
✔️/❌ Smart Audio controls (OSD and CLI)
✔️/❌ Alarm switch
✔️/❌ Barometer
✔️/❌ Blackbox
✔️/❌ LED
✔️/❌ GPS
Or any other features, issues you noticed?
