### ISSUE TITLE
iflight h7 55a

### ISSUE THREAD

**Issue by bspires123** [emuflight/EmuFlight#526]
**Vendor/Model**
Please provide the target name. e.g.IFLIGHT_H743_AIO
Please provide vendor and model of the FC. e.g. Iflight Beast H7 55A AIO (MPU6000)
Please provide a lint to the vendor specifications.  https://shop.iflight-rc.com/index.php?route=product/product&path=20_27_330&product_id=1376
**CLI dump or Unified Target**
Please provide a CLI `dump` or link to unified target. 
[BTFL_cli_20210327_103249.txt](https://github.com/emuflight/EmuFlight/files/6215831/BTFL_cli_20210327_103249.txt)

  Find the unified targets here: https://github.com/betaflight/unified-targets/tree/master/configs/default
(https://github.com/emuflight/EmuFlight/files/6215829/BTFL_cli_20210327_103249.txt)

**Comment by bspires123** [comment]
thank you

**Comment by bspires123** [comment]
sorry newbee!!!

**Comment by nerdCopter** [comment]
@bspires123 , sorry i did not notice this was for `H7`.  H7 support will not exist in 0.3.X, 0.4.X. 
it will only be supported in 1.0.0, thank you.

**Comment by bspires123** [comment]
I don't understand?
so there is no support for this?
can i try emuflight on this f/c/
please help

**Comment by nerdCopter** [comment]
no support for H7 chips yet.  sorry.
must wait for EmuFlight 1.0.0 which is in progress, but far from release.

**Comment by bspires123** [comment]
ok thank you
