### ISSUE TITLE
MATEKF411 target request 

### ISSUE THREAD

**Issue by crocobeans** [emuflight/EmuFlight#530]
**MATEKF411**
Please provide the target name. e.g. `STM32F411`
Please provide vendor and model of the FC. e.g. `
[BTFL_cli_DarwinFPV_20210406_162027.txt](https://github.com/emuflight/EmuFlight/files/6265722/BTFL_cli_DarwinFPV_20210406_162027.txt)
`
Please provide a lint to the vendor specifications.
 e.g https://www.diatoneusa.com/store/p654/New_Diatone_MAMBA_F722_MINI_STACK_Flight_Controller_and_MAMBA_306_ESC.html

**CLI dump or Unified Target**
Please provide a CLI `dump` or link to unified target.
  Find the unified targets here: https://github.com/betaflight/unified-targets/tree/master/configs/default

**Comment by nerdCopter** [comment]
closing since you have working tarket.  re-open if needed.
