### ISSUE TITLE
[target request] FPVCYCLEF401

### ISSUE THREAD

**Issue by nerdCopter** [emuflight/EmuFlight#564]
**Vendor/Model**
* `FPVCYCLEF401`
* `FPVCycle 1S AIO (no Rx) - 1S ONLY`
* https://fpvcycle.com/products/fpvcycle-1s-aio-with-tbs-crossfire-tbs-pro32-nano-vtx

**CLI dump or Unified Target**
* unified: https://github.com/betaflight/unified-targets/blob/master/configs/default/TURC-FPVCYCLEF401.config

requested by @ Silent

**Comment by nerdCopter** [comment]
technically made, but not merged due incomplete PR.
https://github.com/emuflight/EmuFlight/pull/509

**Comment by BeauBrewski** [comment]
Need tested? https://cdn.discordapp.com/attachments/691022009865338950/805548071076364338/EmuFlight_0.3.3_TURC_FPVCYCLEF401_Build_acaae1776.hex

**Comment by nerdCopter** [comment]
https://cdn.discordapp.com/attachments/691022009865338950/850773007253504050/EmuFlight_0.3.4_TURC_FPVCYCLEF401_Build_1330fb967.hex

**Comment by nerdCopter** [comment]
`TURC_FPVCYCLEF401` was merged awhile back for 0.4.0 release
