### ISSUE TITLE
[target request] ZEEZF7V2

### ISSUE THREAD

**Issue by TTGG4400** [emuflight/EmuFlight#592]
Vendor/Model

- ZEEZF7V2
- ZEEZ RC F7 3030 FLIGHT CONTROLLER V2
- https://zeezrc.com/shop/zeez-f7-flight-controller/

CLI dump or Unified Target

- https://github.com/betaflight/unified-targets/blob/master/configs/default/ZEEZ-ZEEZF7V2.config

**Comment by TTGG4400** [comment]
this was entered as a target request - dunno why it doesn't say that though

**Comment by BeauBrewski** [comment]
Needs tested. Check orientation, motors, OSD, all that other stuff. PROPS OFF!
https://cdn.discordapp.com/attachments/547211754845765639/874799667429396490/EmuFlight_0.3.7_ZEEZ_ZEEZF7V2_Build_uncommitted_20210810EDT.hex

**Comment by TTGG4400** [comment]
Unsure of my part in this, if any - should I install this version and test it on my 5" quad that hosts this FC?

**Comment by nerdCopter** [comment]
[EmuFlight_0.3.4_ZEEZ_ZEEZF7V2_Build_5fb813e43.hex.zip](https://github.com/emuflight/EmuFlight/files/6976420/EmuFlight_0.3.4_ZEEZ_ZEEZF7V2_Build_5fb813e43.hex.zip)

**Comment by TTGG4400** [comment]
I installed EmuFlight_0.3.4_ZEEZ_ZEEZF7V2_Build_5fb813e43.hex.zip and all is working except haven't been able to arm since I have a GPS - and I cannot find a CLI cmd to ignore GPS.

**Comment by TTGG4400** [comment]
So - I disabled the GPS - and it armed, and the motors behaved as they should when I moved it about in my hand.

**Comment by nerdCopter** [comment]
@TTGG4400 , thank you!
here is the GPS unlock: https://github.com/emuflight/EmuFlight/wiki/GPS-Lock-Bypass

**Comment by TTGG4400** [comment]
@nerdCopter  Thx for that workaround.  It's perfect.  Let's me wait for sats - or not.

**Comment by TTGG4400** [comment]
It flies nicely too - just got in 2 min before the rains began again.  Thx for the SW.

**Comment by Rubber80** [comment]
Buongiorno Ragazzi, come faccio per installarlo sulla mia zeez v2? lo scarico e lo carico in modalità locale?
è gia testato? scusate ma non sono molto bravo

**Comment by BeauBrewski** [comment]
> Buongiorno Ragazzi, come faccio per installarlo sulla mia zeez v2? lo scarico e lo carico in modalità locale?
> è gia testato? scusate ma non sono molto bravo

Baricare in modalità locale. Non ancora testato.
![image](https://user-images.githubusercontent.com/85623381/129450002-f187afbf-7f69-4b2b-9763-db6393a77e76.png)

**Comment by Rubber80** [comment]
ok grazie. Quando uscirà la versione definitiva?

**Comment by BeauBrewski** [comment]
Dopo aver testato da generosi volontari 😄

**Comment by TTGG4400** [comment]
And today I got in a full flight using  EmuFlight_0.3.4_ZEEZ_ZEEZF7V2_Build_5fb813e43.hex.zip.  Love it.  The Baro and homing arrow and distance home were all spot on for the whole flight.  The 5" quad felt good on the default PIDs that I loaded from the 5" build em from scratch PID presets.  And 50% expo on the sticks.

**Comment by Rubber80** [comment]
ragazzi, purtroppo la vtx non trasmette nessun segnale agli occhiali fpv. cosa posso fare per correggere l'errore?

**Comment by nerdCopter** [comment]
does BlackBox work? do LEDs work?

**Comment by Rubber80** [comment]
ho appena fatto tre lipo, che dire.... stupendo come sempre!!!Ho volato con Pid stock ed eliche rovinate,il Propwash era quasi nulla!! Complimenti! l'unica cosa che sembra non funzionare è "vtx pit mode" in modalità di volo.

**Comment by TTGG4400** [comment]
> * does BlackBox work? do LEDs work?
> * i'll be ready to merge to master, if good.

Blackbox works fine.  I grabbed it using the FC in storage mode, and read it with BF BBLE.  I do not fly with LEDs - so cannot comment on that.

**Comment by Rubber80** [comment]
ho configurato i led sull'arm, e cambiano colore nel momento in cui armo

**Comment by nerdCopter** [comment]
closed by #669
