### ISSUE TITLE
EmuFlight Defaults wiki is still empty eheh

### ISSUE THREAD

**Issue by throttlenerd** [emuflight/EmuFlight#60]
Not a feature request, just didn't find a more suitable category. I'm curious to see/know 1S Tiny Whoop defaults (https://github.com/emuflight/EmuFlight/wiki/Tiny-Whoops#1s-whoops) and 5-inch ones (https://github.com/emuflight/EmuFlight/wiki/5-Inch#heavy-freestyle) -- no info there. Is it really just "not there yet" or is it a coding issue?

Thanks!

**Comment by Quick-Flash** [comment]
we've added preset tunes into the configurator now we just need to add something in the wiki about those preset tunes. Thanks for the reminder
