### ISSUE TITLE
[target request] JHEMCU GHF420AIO

### ISSUE THREAD

**Issue by tzshin** [emuflight/EmuFlight#636]
**Vendor/Model**
JHEF405/JHEMCU GHF420AIO 35A
http://www.jhemcu.com/e_productshow/?39-JHEMCU-JHEMCU-GHF420AIO-35A-39.html

**CLI dump or Unified Target**
https://github.com/betaflight/unified-targets/blob/master/configs/default/JHEF-JHEF405.config

**Comment by BeauBrewski** [comment]
According to the vender link you sent, the Firmware is `BETAFLIGHTF4`
![image](https://user-images.githubusercontent.com/85623381/124523092-24be3480-ddbb-11eb-8ef9-c8cd70b3f30f.png)

Try flashing the EmuFlight `BETAFLIGHTF4` target and see if that works for you. (Props off, check orientation, etc)

Let us know if that works.

**Comment by tzshin** [comment]
Haven't been able to build and test the whole quad due to slow ships. But with slight comparison between BETAFLIGHTF4 config and cli dump, it should be right one.

The default firmware on the fc seems to be a custom (or modified) one, tagged with a confusing unique firmware target.

**Comment by soukron** [comment]
FWIW I flashed betaflightf4 target and even when apparently everything works (motors, osd, gyro, sbus, etc) I can't arm nor see the voltage of the lipo in the OSD. I must be missing something or better yet the target isn't the right one.

**Comment by BeauBrewski** [comment]
> FWIW I flashed betaflightf4 target and even when apparently everything works (motors, osd, gyro, sbus, etc) I can't arm nor see the voltage of the lipo in the OSD. I must be missing something or better yet the target isn't the right one.

@soukron Got a copy of your BF and Emu dumps for your build?
