### ISSUE TITLE
Very need gps_rescue_alt_mode = FIXED_ALT & osd_nvario not work

### ISSUE THREAD

**Issue by aLDime** [emuflight/EmuFlight#653]
**Is your feature request related to a problem? Please describe.**
1. The accumulation of altitude is unacceptable, the copter at some point rises very high and loses the signal!
2. The display of the rate of climb / fall heights doesn't work on OSD

**Describe the solution you'd like**
1. Need gps_rescue_alt_mode = FIXED_ALT
2. Bug fix

**Describe alternatives you've considered**
All this is in BF and iNav, this is Must Have!

**Additional context**
[gps_rescue_initial_alt = 70, but altude increased up to 150m](https://youtu.be/14-ZTQZEl6E?t=285)
[osd_nvario not work](https://youtu.be/71q_nfMZFs8)

**Comment by nerdCopter** [comment]
What version are you running? i think there was baro calculation fox in dev versions, not yet released.
do you know about the dev-master builds?
