### ISSUE TITLE
[Bug Report] Enabling GPS or GPS+Telemetry in Configurator sandbags flight controller requiring reflash of firmware. 

### ISSUE THREAD

**Issue by BeauBrewski** [emuflight/EmuFlight#655]
**Describe the bug**

1. Fresh configure of MatekF405SE works until GPS is enabled in configurator and saved. Then cannot reconnect to fc unless booted in DFU mode and reflashed. Confirmed works in BF. Tried on 0.3.3 and 0.3.4. 
2. Fresh configure of KakuteF7 HD works until GPS _and_ Telemetry are both enabled in configurator and saved. One or the other on is fine. Then cannot reconnect to fc unless booted in DFU mode and reflashed. 

**To Reproduce**
1. On MatekF405SE, enable GPS in configurator, save/exit, unplug, and try to reconnect. 
2. On KakuteF7 HD, enable GPS _and_ Telemetry in configurator, save/exit, unplug, and try to reconnect. 

**Expected behavior**
Enabling of the GPS or GPS+Telemetry to save without sand bagging the flight controller, and being able to use features to fly long range with GPS and/or Telemetry. 

**Flight controller configuration**
_Need diff's from pilots reporting issue._

**Setup / Versions**
1.   FC: MatekF405SE
     GPS: Flywoo GM8 Mini V2
     Soldered to UART5
2.  FC: KakuteF7 HD
     Pilot speaks French. 

**Additional context**
1. MatekF405SE works in BF with no hardware changes. Emu was fresh install with no copying of BF diff or dump.

**Comment by nerdCopter** [comment]
so many targets to confuse.
is kakute the proper target for certain? 
we have
```
KAKUTEF7
KAKUTEF7HDV
KAKUTEF7V15  (V2 in BF)
KAKUTEF7MINIV1
KAKUTEF7MINIV2
KAKUTEF7MINIV3
```

**Comment by BeauBrewski** [comment]
Attempting to verify. _Should_ be the `KAKUTEF7HDV`.

**Comment by nonoreb** [comment]
Hello, 
Did you find any solution to this ? I have the same problem with KAKUTEF7V15, I have to reflash (0.4.0) because I cannot acces fc anymore after enabling GPS.

**Comment by nerdCopter** [comment]
> Hello, Did you find any solution to this ? I have the same problem with KAKUTEF7V15, I have to reflash (0.4.0) because I can't acces fc anymore after enabling GPS.

try `KAKUTEF7HDV` & let us know.
  if still fails, we need to investigate target resources and we request cli dumps of BF vs Emu.

**Comment by Kaiowarez** [comment]
Ahhh I was going to add GPS drivers for those targets I'll fix it
later today

**Comment by nerdCopter** [comment]
Needs testing: https://github.com/emuflight/EmuFlight/pull/850 (`MATEKF405SE`)
[EmuFlight_0.4.1_MATEKF405SE_Build_ad3b78da3.hex.zip](https://github.com/emuflight/EmuFlight/files/9284598/EmuFlight_0.4.1_MATEKF405SE_Build_ad3b78da3.hex.zip)

**Comment by loutwice** [comment]
> @nerdCopter @Kaiowarez  

hi buddieeees, @Kaiowarez did you get time to add gps driver for the kakute?

**Comment by nerdCopter** [comment]
@loutwice , which target do you need. i suppose i can look.  I have the MATEKF405SE .zip above, that was never tested by anyone.
