### ISSUE TITLE
Request for target: TMotor F4 HD for DJI System

### ISSUE THREAD

**Issue by mrminikwad** [emuflight/EmuFlight#66]
Guys no I'm gonna have to go back to betaflight aaahhh. Ok jokes aside the tmotor is very new so totally cool with it

**Comment by nerdCopter** [comment]
Issue Clarification: Older TMOTOR F4 (non-HD) is supported with target TMOTORF4.
New HD version for DJI system is not.

**Comment by spawn94260** [comment]
I confirm, T-MOTOR F4 HD not supported by T-MOTOR F4 (Non HD) target :-(
