### ISSUE TITLE
shark byte canvas mode

### ISSUE THREAD

**Issue by neverknownbetter** [emuflight/EmuFlight#700]
Enable OSD to be displayed through serial port 
Add OSD_displayport_device = MSP and displayport_msp_serial =  into CLI.

**Comment by th8tredude** [comment]
I would also like this to be addressed

**Comment by nerdCopter** [comment]
PR #775 working. 
requires https://github.com/emuflight/EmuConfigurator/pull/449

known quirks:
* DJI OSD element like corsshair no longer on screen.
* vtx OSD element not synced with sharkbyte/hdzero.
* may rework this code to allow legacy OSD element placement for legacy SD (non-HD).
