### ISSUE TITLE
[Target Request] DARWINF722HD

### ISSUE THREAD

**Issue by DMAXYANG** [emuflight/EmuFlight#708]
**Vendor/Model**
DARWINF722HD

DARWINF722HD Flight Controller
https://darwinfpv.com/products/darwinfpv-fpv-esc-xt60-f7-dji-flight-controller-flysky-racing-drone-betaflight-fc-100a-3-6s-blheli_32-4in1-dshot1200

CLI dump or Unified Target
https://github.com/betaflight/unified-targets/blob/master/configs/default/DAFP-DARWINF722HD.config

**Comment by BeauBrewski** [comment]
Needs tested!
Check gyro orientation, motor arrangement, flash, vtx control, everything else if possible please update here
PROPS OFF FOR SAFETY

[EmuFlight_0.4.0_DARWINF722HD_Build_acce1883f.zip](https://github.com/emuflight/EmuFlight/files/7532811/EmuFlight_0.4.0_DARWINF722HD_Build_acce1883f.zip)

**Comment by BeauBrewski** [comment]
Kabab FPV reports that it works and flies great and doesn't understand why anyone uses betaflight and wants to know how to make this target official.
