### ISSUE TITLE
No Gyro detected on Holybro Kakute F7 Flight Controller AIO.

### ISSUE THREAD

**Issue by boof64** [emuflight/EmuFlight#72]
Аfter flashing the board Holybro Kakute F7 Flight Controller AIO I have the same error.
Issue #39 didn't help me (different target)

REM: after flashing BetaFlight i have the dialog box with question like "Theare are special settings for this board....".

**Comment by Quick-Flash** [comment]
try the kakutaf7hdv target and see if that works

**Comment by boof64** [comment]
> try the kakutaf7hdv target and see if that works

Thank you! I'll test it

**Comment by Rennings1991** [comment]
Did this work? I'm having the same issue with my kakute f7 aio v1.5 and would really like to run emuflight on it. I'm not sure what target I need to flash.

**Comment by nerdCopter** [comment]
@Rennings1991 there will be a v1 and v2 kukute in 0.3.0 release

**Comment by boof64** [comment]
> Did this work? I'm having the same issue with my kakute f7 aio v1.5 and would really like to run emuflight on it. I'm not sure what target I need to flash.

Yes, its work for me.
