### ISSUE TITLE
[target driver] NewBeeDrone BeeBrainPro DSM target gyro not detected. 

### ISSUE THREAD

**Issue by BeauBrewski** [emuflight/EmuFlight#735]
**Describe the bug**
BeeBrainPro DSM target is not showing gyro or accelerometer info when flashing. 

**To Reproduce**
Flash `BEEBRAIN_PRO_DSM` target to appropriate flight controller and connect to configurator. 

**Expected behavior**
Expect Gyro/Accelerometer to be detected.

**Additional context**
NBD's BeeBrainPro DSM target uses a different gyro, `BMI160`, where the EmuFlight target only has `MPU6000`. Need to add if/else code for the correct gyro info. 

Note: keep an eye on VTx functionality in the process.

**Comment by nerdCopter** [comment]
this gets the bmi160 gyro working, nothing more: https://github.com/nerdCopter/EmuFlight_nerdRepo/commit/f7c36937cd5d201a847be0a89ae48d2abcdc9d08

**Comment by BeauBrewski** [comment]
I'm doing the double define trick like I did with the `MATEKF411RX/CRAZYBEEF4` target. That should keep from losing compatibility with any older boards that still had MPU6000 on the DSM models.

**Comment by nerdCopter** [comment]
@BeauBrewski , please do your magic, thank you very much!

**Comment by nerdCopter** [comment]
backported to 0.4.2 release assets
