### ISSUE TITLE
Kakute f7 probleme uart 6

### ISSUE THREAD

**Issue by fcfpv** [emuflight/EmuFlight#74]
Je vous expose mon souci 
Emu 2.12
Kakute f7 release f7hdv du 13.12.2019 tous fonctionnais jusque la .
Mais depuis quelque jours impossible de changer de fréquence via l'osd .j ai reflasher et réinstallé et tjs pareil.par curiosité je flash sous betaflight et la aucun souci ça marche
Un avis les gars?

**Comment by gretel** [comment]
english, please.
