### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by hyptx** [emuflight/EmuFlight#743]
I have a new Betafpv meteor 65 and flashed 0.4.0. The craft wouldn't take off and I saw that it was because of 100% CPU usage. I tinkered around and turned off as many extra features as I could. But still 100%. I then dropped the loop to 4k and was able to get it to take off, but it didn't fly properly.

I had another pilot tell me to just use 0.3.4 because the new Emu has a bunch of new features and is still in development. So I did. My Meteor 65 flies perfect on 0.3.4 and the cpu usage is only in the 20's.

Any suggestions about what might be going on with the AIO board and the version 0.4.0?

**Comment by nerdCopter** [comment]
4k/4k is  a good option if it was 100% cpu.
I would personally turn rc-smoothing to `interpolation` and something like `21` to use less cpu.
Defaults in EmuFlight are for 5" quad -- try raising gyro LPF to maybe 150 or 160 and dterm LPF1 to maybe 190 or 200 for 65mm whoop. turn off dterm lpf2.
if it's still high cpu, consider disabling dynamic-filter and changing dLPF1 to PT2.

please join discord for more assistance.
