### ISSUE TITLE
[Target Request] GEPRC_F722_AIO (ICM42688P)

### ISSUE THREAD

**Issue by salem83** [emuflight/EmuFlight#744]
**Vendor/Model**
* Please provide the target name ???
* GEPRC GEP-F722-45A AIO
* https://geprc.com/product/geprc-gep-f722-45a-aio/

**CLI dump or Unified Target**
* [BTFL-GEPRC_F722_AIO-defaults.txt](https://github.com/emuflight/EmuFlight/files/7797203/BTFL-GEPRC_F722_AIO-defaults.txt)
* https://geprc.com/wp-content/uploads/2020/01/CineLog35-HD-TBS-4.2.3-1.txt
* https://github.com/betaflight/unified-targets/blob/master/configs/default/GEPR-GEPRC_F722_AIO.config

**Comment by BeauBrewski** [comment]
Needs tested!
Check gyro orientation, motor arrangement, flash, osd, vtx control, everything else if possible please update here with feedback that it works or needs improvement.
PROPS OFF FOR SAFETY

[EmuFlight_0.4.0_GEPRC_F722_AIO_Build_29fdb64ca.zip](https://github.com/emuflight/EmuFlight/files/7826784/EmuFlight_0.4.0_GEPRC_F722_AIO_Build_29fdb64ca.zip)

**Comment by BeauBrewski** [comment]
Working on test target
https://github.com/emuflight/EmuFlight/pull/891

**Comment by BeauBrewski** [comment]
Needs tested! ICM42688P gyro target.
Works on bench and gyro detected.

[EmuFlight_0.4.2_GEPRC_F722_AIO_icm42x_0c9bb946d.zip](https://github.com/emuflight/EmuFlight/files/11587180/EmuFlight_0.4.2_GEPRC_F722_AIO_icm42x_0c9bb946d.zip)

**Comment by nerdCopter** [comment]
@salem83 , have you tested?

**Comment by nerdCopter** [comment]
resolved by:
https://github.com/emuflight/EmuFlight/pull/903
https://github.com/emuflight/EmuFlight/pull/1015
closing ticket

**Comment by salem83** [comment]
@nerdCopter Sorry, didn't had time back then. And in meanwhile, i switched back to BF.
