### ISSUE TITLE
No voltage on Meteor65 (BetaFPV F411)

### ISSUE THREAD

**Issue by skrat** [emuflight/EmuFlight#746]
I flashed 0.4.0 on my BetaFPV Meteor65 tiny whoop. I used BETAFPVF411 target.

The yaw axis on accelerometer seems inverted, but worse, the voltage reading is 0.1 or 0.0 V.

I can't actually take off with it, tried angle mode and then gave up.

Lemme know if you need anything, I'm eager to try Emuflight on this whoop.

**Comment by skrat** [comment]
[BTFL_cli_Meteor65_20220116_175512.txt](https://github.com/emuflight/EmuFlight/files/7878800/BTFL_cli_Meteor65_20220116_175512.txt)

This is known working BF conf. I tried assigning the resources in Emuflight, but it led to being unable to connect with USB again, and I had to enter DFU using a physical button and re-flashing.

**Comment by glebtv** [comment]
My meteor65 mostly works for me with a MATEKF411RX target (I have frsky spi version)

Here's a diff
[BTFL_cli_Meteor65_20220115_163256.txt](https://github.com/emuflight/EmuFlight/files/7886948/BTFL_cli_Meteor65_20220115_163256.txt)

BUT, I have kinda a lot of rx loss failsafes, i think it was better on betaflight.

**Comment by glebtv** [comment]
Voltage works for me, here are the settings

![image](https://user-images.githubusercontent.com/1041407/149889673-b5219a86-92b2-4f19-91d1-6ef27819fdf9.png)

**Comment by glebtv** [comment]
Also, I tried your betaflight settings and somewhy with them i'm missing one ESC.
Here are my betaflight settings
[meteor65_v2.txt](https://github.com/emuflight/EmuFlight/files/7887147/meteor65_v2.txt)

My flight controller is labelled 1S F4 FR VTX v1.1

**Comment by nerdCopter** [comment]
* some discord history concurs to use MATEKF411 or MATEKF411RX for SPI version.
* make sure motor `resource`s in CLI are the same from BF dump.
* i also read to find blheli (non-chrome) and reflash ESC's if nothing else works. (i.e. chrome version may introduce error -- i dont know for fact, just passing information along)

**Comment by skrat** [comment]
BETAFPVF411 is what I used in BF 4.2.11 (latest stable) and it works flawlessly. ESCs are flashed with Bluejay, and again, works flawlessly in BF. Would @Kaiowarez know anything about this? Also @nerdCopter I see you being co-author of the BETAFPVF411 target. What is this target for then?

**Comment by nerdCopter** [comment]
@Kaiowarez may know, or maybe @BeauBrewski could assist.  my only part in the original is that i click the merge buttons, therefore it lists me as co-author, but not really true.

**Comment by BeauBrewski** [comment]
@skrat I think you may be using wrong target as your BF dump text says its 
`board_name BETAFPVF411RX`

Try the test file hex for this target:
https://github.com/emuflight/EmuFlight/issues/486#issuecomment-972940387

**Comment by BeauBrewski** [comment]
@skrat Any feedback on the test target `BETAFPVF411RX`?

**Comment by BeauBrewski** [comment]
Wrong target flashed according to OP's betaflight dump. 
Closing issue. 
Will open new issue if there is problem with correct target.
