### ISSUE TITLE
REQUEST FOR TARGET - T-MOTOR F7

### ISSUE THREAD

**Issue by FlyTilliDie** [emuflight/EmuFlight#76]
Would love to have a target for the Tmotorf7. I'll gladly test it. I really prefer EMU over BF

**Comment by nerdCopter** [comment]
is this a duplicate of #75 ?

**Comment by FlyTilliDie** [comment]
> is this a duplicate of #75 ?


I think so. The difference is just the HD I believe. Not sure if that plus a part

**Comment by gretel** [comment]
@Kaiowarez can you help out?

**Comment by Kaiowarez** [comment]
Don't we have this? But I can make it later

**Comment by gretel** [comment]
sorry i wasnt sure so many merges :) thank you!

**Comment by Kaiowarez** [comment]
Should have this already, if not it's prolly on my repo needing testing lemme know if someone wants to work on getting this tested

**Comment by Kaiowarez** [comment]
Done with target please close.
