### ISSUE TITLE
TARGET REQUEST: IFLIGHT_BLITZ_F722 (BMI270)

### ISSUE THREAD

**Issue by BeauBrewski** [emuflight/EmuFlight#765]
**Vendor/Model**
IFLIGHT_BLITZ_F722
IFlight Blitz F7 Flight Controller
https://shop.iflight-rc.com/quad-parts-cat20/electronics-cat27/BLITZ/BLITZ-F7-Flight-Controller-Pro1692

**CLI dump or Unified Target**
https://github.com/betaflight/unified-targets/blob/master/configs/default/IFRC-IFLIGHT_BLITZ_F722.config

NOTE: NEEDS BMI270 DRIVERS UPDATED AS NO LONGER USING MPU6000 CHIPS

**Comment by BeauBrewski** [comment]
Needs tested!
Check gyro orientation, motor arrangement, flash, osd, vtx control, everything else if possible please update here
PROPS OFF FOR SAFETY

**Comment by etsme** [comment]
Has there been any further testing on this FC ?

**Comment by BeauBrewski** [comment]
@etsme none as of yet. If you have a flight controller with this target, you are welcome to test it and give feed back. That is how updates get made on new targets.

**Comment by BeauBrewski** [comment]
Working on test target
https://github.com/emuflight/EmuFlight/pull/890
