### ISSUE TITLE
GEPRC F411 35A AIO (STM32F411)

### ISSUE THREAD

**Issue by MaikFPV** [emuflight/EmuFlight#766]
Vendor/Model
GEP-F411-35A AIO
GEPRC Flight Controller F4 35A AIO e.g. Cinelog 30
https://geprc.com/product/gep-f411-35a-aio-f411-fc-35a-2-6s-8bits-bls-esc-25-5mm-m2/

CLI dump or Unified Target
https://github.com/betaflight/unified-targets/blob/master/configs/default/GEPR-GEPRCF411_AIO.config

I tried GEPRCF411_PRO but motor map is not correct.

**Comment by BeauBrewski** [comment]
Needs tested!
Check gyro orientation, motor arrangement, flash, osd, vtx control, everything else if possible please update here

PROPS OFF FOR SAFETY!
[EmuFlight_0.4.0_GEPRCF411_AIO_Build_e275b128d.zip](https://github.com/emuflight/EmuFlight/files/8223718/EmuFlight_0.4.0_GEPRCF411_AIO_Build_e275b128d.zip)

**Comment by MaikFPV** [comment]
Tested it and it works - UART 1 is twice in settings?! Will test more this weekend. Thanks you BeauBrewski
![Bildschirmfoto 2022-03-11 um 13 35 42](https://user-images.githubusercontent.com/15635382/157868456-3c1c3ec5-7ae2-43a4-acd2-cd73be44892a.png)

**Comment by BeauBrewski** [comment]
Hahahaha, I think I know what the issue is, but let me double check with @Kaiowarez.

**Comment by BeauBrewski** [comment]
@MaikFPV I had a brain fart when setting up the softserial pins. The target above has been updated, if you want to reflash and let me know if second UART1 is gone. Thank you!

**Comment by MaikFPV** [comment]
Fixed! Thanks a lot!
![Bildschirmfoto 2022-03-11 um 14 40 41](https://user-images.githubusercontent.com/15635382/157879007-8a8624d1-257d-48c1-8aab-4661cddcc773.png)

**Comment by BeauBrewski** [comment]
Awesome! Feedback is much appreciated for as many features as possible or available:
✔️/❌ Flash
✔️/❌ Gyro
✔️/❌ Accelerometer
✔️/❌ Motors
✔️/❌ Onboard ADC
✔️/❌ OSD (analog)
✔️/❌ Smart Audio controls (OSD and CLI)
✔️/❌ Alarm switch
✔️/❌ Barometer
✔️/❌ Blackbox
✔️/❌ LED
✔️/❌ GPS
Or any other features or issues you notice

**Comment by nerdCopter** [comment]
:)
i really like the ✔️/❌ format if pilots can feedback like so, or at least `Y`/`N` if emojis are a problem.

**Comment by Shreyash-Patil470** [comment]
I have bricked my GEPRC F411 AIO, as in when I plug it into a PC I get a red constant light. How do I fix it?

**Comment by nerdCopter** [comment]
not bricked. press and hold boot-button, then plug in USB.  you will gain DFU for re-flashing.
