### ISSUE TITLE
[Firmware Bug Report] MAMBAF722/MAMBAF722I2C gyro MPU6500 addition

### ISSUE THREAD

**Issue by BeauBrewski** [emuflight/EmuFlight#803]
Gyro changes to Diatone Mamba MK2  FC have caused current MPU6000 setup on targets `MAMBAF722/MAMBAF722I2C` not to work.

Contact with Diatone has returned with the gyro change being MPU6500.

https://www.diatone.us/collections/dji/products/mamba-dji-f722-mk2-50a-6s-8bit-flight-controller-stack

Will add additional definitions for the MPU6500 gyro.

**Comment by nerdCopter** [comment]
jeez, hardware modifications causing complications.
Thanks @BeauBrewski !

**Comment by BeauBrewski** [comment]
Needs tested!
Please check gyro function, board orientation, motors, flight, etc.

[EmuFlight_0.4.0_MAMBAF722I2C_Build_bc1e90621.zip](https://github.com/emuflight/EmuFlight/files/8585309/EmuFlight_0.4.0_MAMBAF722I2C_Build_bc1e90621.zip)

**Comment by BeauBrewski** [comment]
Tested by @Noodles on the discord page and flew great. Mergible if approved.

**Comment by noodles** [comment]
@BeauBrewski - you've got the wrong noodles. I have no idea what this project is - looks cool though :)

**Comment by BeauBrewski** [comment]
Hahahah, Oops, didn't mean to tag you. Sorry about that!

**Comment by BeauBrewski** [comment]
Closing, Merged.
