### ISSUE TITLE
Target request HAKRCF411D

### ISSUE THREAD

**Issue by torju01** [emuflight/EmuFlight#805]
Vendor and model:  HAKRC F411 AIO 20A (F4126)
target name:  HAKRCF411D

vendor link:  http://www.hikrc.com/pd.jsp?id=63#_pp=103_435

unified targets:  https://github.com/betaflight/unified-targets/blob/master/configs/default/HARC-HAKRCF411D.config

**Comment by BeauBrewski** [comment]
I actually have this exact FC and it came with `MATEKF411` flashed.  Flies great on Emuflight with that target.

**Comment by BeauBrewski** [comment]
Awesome! I've had good luck with that FC so far. Other sellers websites also recommend `MATEKF411` for it.

https://pyrodrone.com/products/hakrc-f4126-blheli_s-20a-whoop-aio-fc

**Comment by BeauBrewski** [comment]
Closing for now as most sites recommend `MATEKF411` for this board, and my own personal FC came with `MATEKF411` flashed for BF, and op has tested and flown with no problems.
