### ISSUE TITLE
Osd Crossfire dbm and tx power

### ISSUE THREAD

**Issue by AnotherRumor** [emuflight/EmuFlight#828]
Wondering if it is possible to use the crossfire dbm and tx power osd to show ELRS dbm and tx power output? Or of there is another way to do this that I'm not aware of.

**Comment by nerdCopter** [comment]
if it's not working with this info from the wiki, then someone has to fix/add some code.
https://github.com/emuflight/EmuFlight/wiki/CRSF-LQ

**Comment by nerdCopter** [comment]
SNR Fixed in #833 .
Power requires pilot to use "wind-mode" in ELRS as per ELRS dev.
