### ISSUE TITLE
No COM port after flashing 0.4.1 TMTR_TMPACERF7_29_07_2022

### ISSUE THREAD

**Issue by B-nutze-RR** [emuflight/EmuFlight#851]
**Describe the bug**
- 0.4.0 is running, but i get no COM port after flashing 0.4.1 - tested on 2 "T-Motor Pacer SINGEL Sided F7" FCs...but after reconnect it works, is that normal ?

**To Reproduce**
- no steps given

**Setup / Versions**
 - T-Motor Pacer SINGEL Sided F7
 - Other components [RX, VTX, brand / model for all of them, firmware version where applicable];
 - how are the different components wired up.

**Additional context**
- Switching versions seems to need a reconnect and "reflashing " the same firmware gives a working com port when it reboots

**Comment by nerdCopter** [comment]
After flashing, many FC's require USB unplug & replug. this was the case with  0.4.0, 0.3.X as well.
Is this what you're describing?

**Comment by B-nutze-RR** [comment]
Absolutely, i guess it's because i never experienced it with any of my Helio/Strix  setups and i now slowly add more F7/H7 FCs 😆👌
