### ISSUE TITLE
No telemetry with fport

### ISSUE THREAD

**Issue by albebert** [emuflight/EmuFlight#86]
Hello,

i wan't to use the fport for my setup on a HGLRC f4 stack.

fport firmware OK, bind OK, channels are responding.

but i receive no telemetry from the FC.

fport is connecter on sbus inverted (UART1)

a diff of my setup :

# EmuFlight / OMNIBUSF4 (OBF4) 0.1.0 Sep 16 2019 / 22:56:24 (3956d2f50) MSP API: 1.40

board_name 
manufacturer_id 

# name
name Gecko

# resources

# mixer

# servo

# servo mix

# feature
feature -RX_PARALLEL_PWM
feature -DYNAMIC_FILTER
feature RX_SERIAL
feature TELEMETRY
feature LED_STRIP
feature ANTI_GRAVITY

# beeper
beeper -GYRO_CALIBRATED
beeper -RX_LOST
beeper -RX_LOST_LANDING
beeper -DISARMING
beeper -ARMING
beeper -ARMING_GPS_FIX
beeper -BAT_CRIT_LOW
beeper -BAT_LOW
beeper -GPS_STATUS
beeper -RX_SET
beeper -ACC_CALIBRATION
beeper -ACC_CALIBRATION_FAIL
beeper -READY_BEEP
beeper -DISARM_REPEAT
beeper -ARMED
beeper -SYSTEM_INIT
beeper -ON_USB
beeper -BLACKBOX_ERASE
beeper -CRASH FLIP
beeper -CAM_CONNECTION_OPEN
beeper -CAM_CONNECTION_CLOSED
beeper -RC_SMOOTHING_INIT_FAIL

# beacon
beacon RX_LOST
beacon RX_SET

# map
map TAER1234

# serial
serial 0 64 115200 57600 0 115200
serial 2 8192 115200 57600 0 115200

# led
led 0 0,0::L:2
led 1 1,0::C:2
led 2 2,0::C:2
led 3 3,0::S:0

# color

# mode_color

# aux
aux 0 0 7 1800 2100 0 0
aux 1 1 1 900 1300 0 0
aux 2 13 6 1700 2100 0 0
aux 3 36 4 1700 2100 0 0

# adjrange

# rxrange

# vtx

# rxfail

# master
set gyro_lowpass2_hz = 300
set gyro_notch1_cutoff = 300
set gyro_notch2_cutoff = 100
set acc_lpf_hz = 10
set acc_calibration = -127,-3,231
set mag_hardware = NONE
set baro_hardware = NONE
set rssi_scale = 41
set rc_interp_ch = RP
set rc_smoothing_input_type = PT1
set rc_smoothing_derivative_type = OFF
set serialrx_provider = FPORT
set serialrx_inverted = ON
set motor_pwm_protocol = DSHOT600
set vbat_scale = 112
set ibata_scale = 1000
set imu_dcm_kp = 2500
set imu_dcm_ki = 0
set gps_distance_limit = 1000
set deadband = 5
set runaway_takeoff_prevention = ON
set ibus_sensor = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
set osd_warn_arming_disable = OFF
set osd_warn_batt_not_full = OFF
set osd_warn_batt_warning = ON
set osd_warn_batt_critical = ON
set osd_warn_visual_beeper = OFF
set osd_warn_crash_flip = ON
set osd_warn_esc_fail = OFF
set osd_warn_core_temp = OFF
set osd_cap_alarm = 700
set osd_distance_alarm = 2562
set osd_esc_temp_alarm = -1
set osd_esc_rpm_alarm = 70
set osd_ah_max_pit = 0
set osd_ah_max_rol = 0
set osd_tim1 = 127
set osd_tim2 = 10260
set osd_vbat_pos = 2465
set osd_rssi_pos = 2497
set osd_tim_1_pos = 2282
set osd_flymode_pos = 2444
set osd_ah_pos = 234
set osd_current_pos = 2272
set osd_mah_drawn_pos = 2305
set osd_craft_name_pos = 42
set osd_disarmed_pos = 2282
set osd_stat_tim_2 = OFF
set osd_stat_max_spd = OFF
set osd_stat_min_batt = OFF
set osd_stat_battery = ON
set osd_stat_min_rssi = OFF
set osd_stat_max_curr = OFF
set osd_stat_used_mah = OFF
set osd_stat_bbox = OFF
set osd_stat_bb_no = OFF
set vtx_band = 5
set vtx_power = 4
set vtx_freq = 5658
set usb_hid_cdc = ON

# profile
profile 0

set throttle_boost = 0

# rateprofile
rateprofile 0

set tpa_rate_p = 10
set tpa_rate_i = 0
set tpa_rate_d = 114
set tpa_breakpoint = 25600
set throttle_limit_type = MANUAL
set throttle_limit_percent = 0

thanks in advance

**Comment by gretel** [comment]
@albebert looks like you your are inverting twice:

```
set serialrx_inverted = ON
```
