### ISSUE TITLE
[TARGET REQUEST]: MAMBAF722_2022A (BMI270)

### ISSUE THREAD

**Issue by BeauBrewski** [emuflight/EmuFlight#862]
**Vendor/Model**
 `MAMBAF722_2022A` 
 MAMBA MK4 F722 APP
 https://www.diatone.us/products/mb-mk4-f722-app-fc
 
![image](https://user-images.githubusercontent.com/85623381/188011539-cd402bb5-e414-4783-adff-7ae60b4bc798.png)

https://github.com/betaflight/unified-targets/blob/master/configs/default/DIAT-MAMBAF722_2022A.config
https://github.com/betaflight/unified-targets/blob/master/configs/default/DIAT-MAMBAF722_2022B.config

**Comment by BeauBrewski** [comment]
Working on test target
https://github.com/emuflight/EmuFlight/pull/890

**Comment by nerdCopter** [comment]
resolved by https://github.com/emuflight/EmuFlight/pull/954
