### ISSUE TITLE
Target Request: SPEEDYBEEF7MINI 

### ISSUE THREAD

**Issue by baboon9999** [emuflight/EmuFlight#870]
**SpeedyBee**
* SPEEDYBEEF7MINI 
* SPEEDYBEEF7MINI 
* Link to FC Specs https://www.speedybee.com/speedybee-f7-mini-35a-3-6s-8-bit-flight-controller-stack/)

*Cli Dump
Currently running version 0.4.0 dated Feb 2022
[EMUF_cli_20220928_213141.txt](https://github.com/emuflight/EmuFlight/files/9668735/EMUF_cli_20220928_213141.txt)

**Comment by nerdCopter** [comment]
closing this.  when we get feedback/results of issue #753 , then we can merge to master and release 0.4.1 inside the configurator
