### ISSUE TITLE
[Firmware/Target Bug] BETAFPVF411RX no Gyro MPU6500/BMI270 functionality

### ISSUE THREAD

**Issue by BeauBrewski** [emuflight/EmuFlight#874]
**Describe the bug**
Target `BETAFPVF411RX` needs MPU6500 functionality added to it.

On a BetaFPV 65s that is not detecting gyro.
Per "status" on BF CLI, it is an MPU6500 gyro from OwenSR on Discord server.

**Comment by Harl-Towne** [comment]
The `BETAFPVF411` target also has the same issue for me.

**Comment by nerdCopter** [comment]
please test and feedback.  if HD versions are needed, i'll have to do separately upon request. 
[EmuFlight_0.4.1_BETAFPVF411_Build_cf388beed.hex.zip](https://github.com/emuflight/EmuFlight/files/10743891/EmuFlight_0.4.1_BETAFPVF411_Build_cf388beed.hex.zip)
[EmuFlight_0.4.1_BETAFPVF411RX_Build_cf388beed.hex.zip](https://github.com/emuflight/EmuFlight/files/10743892/EmuFlight_0.4.1_BETAFPVF411RX_Build_cf388beed.hex.zip)

**Comment by nerdCopter** [comment]
@Harl-Towne , any feedback on the HEX posted above?

**Comment by Harl-Towne** [comment]
> @Harl-Towne , any feedback on the HEX posted above?

The [EmuFlight_0.4.1_BETAFPVF411_Build_cf388beed.hex.zip](https://github.com/emuflight/EmuFlight/files/10743891/EmuFlight_0.4.1_BETAFPVF411_Build_cf388beed.hex.zip) HEX flashes but still shows the `NO_GYRO` arming disable flag. 

The original issue mentions the MPU6500 gyro but my FC uses the BMI270. I couldn't find a BETAFPV FC with the MPU6500 so just to make sure we're on the same page I'm having issues with the [F4 1S 5A AIO Brushless Serial ELRS Flight Controller](https://betafpv.com/products/f4-1s-5a-aio-brushless-flight-controller-elrs-2-4g). Not sure if there are multiple boards with the same targets or if this board has been made with multiple gyros.

Hope the info there helps, let me know if you need anything else.

**Comment by nerdCopter** [comment]
> > @Harl-Towne , any feedback on the HEX posted above?
> 
> The [EmuFlight_0.4.1_BETAFPVF411_Build_cf388beed.hex.zip](https://github.com/emuflight/EmuFlight/files/10743891/EmuFlight_0.4.1_BETAFPVF411_Build_cf388beed.hex.zip) HEX flashes but still shows the `NO_GYRO` arming disable flag.
> 
> The original issue mentions the MPU6500 gyro but my FC uses the BMI270. I couldn't find a BETAFPV FC with the MPU6500 so just to make sure we're on the same page I'm having issues with the [F4 1S 5A AIO Brushless Serial ELRS Flight Controller](https://betafpv.com/products/f4-1s-5a-aio-brushless-flight-controller-elrs-2-4g). Not sure if there are multiple boards with the same targets or if this board has been made with multiple gyros.
> 
> Hope the info there helps, let me know if you need anything else.

miscommunication; Emu does not support BMI270

**Comment by nerdCopter** [comment]
BETAFPV411 BMI270 support resolved in master
- https://github.com/emuflight/EmuFlight/pull/930
- https://github.com/emuflight/EmuFlight/pull/937
- already tested

BETAFPVF411RX BMI270 and MPU6500 support in 
- https://github.com/emuflight/EmuFlight/pull/947
- needs testing
