### ISSUE TITLE
[TARGET REQUEST]  FOXEERF722V4 (ICM42688P)

### ISSUE THREAD

**Issue by BeauBrewski** [emuflight/EmuFlight#876]
**Vendor/Model**
Foxeer F722 V4 Mini FC
`FOXEERF722V4`
https://www.foxeer.com/foxeer-f722-v4-mini-flight-controller-20-20mm-betaflight-g-448

**CLI dump or Unified Target**
https://github.com/betaflight/unified-targets/blob/master/configs/default/FOXE-FOXEERF722V4.config

 *NOTE* ICM42688 GYRO *AND* MPU6000

**Comment by nerdCopter** [comment]
* unfinished code here: https://github.com/nerdCopter/EmuFlight_nerdRepo/tree/20220930_ICM426xx
* i've been side-tracked yet again, but on my to-do list.
* thus far, i've neglected to add the code related to the defines (ICM42688P_CS_PIN, ICM42688P_SPI_INSTANCE, GYRO_ICM42688P_ALIGN, ACC_ICM42688P_ALIGN)

**Comment by pavankmr853** [comment]
how to upload this config file bro

**Comment by nerdCopter** [comment]
> how to upload this config file bro

we dont have working code yet

**Comment by nerdCopter** [comment]
* https://github.com/emuflight/EmuFlight/pull/891
* I'll attempt to create this target.

**Comment by nerdCopter** [comment]
Needs thorough testing and feedback.
Test gyro/accel on USB (Configurator sensors tab) first.
Test orientattion
Then test props off.
Then test-hover.
check motor temperatures, do not full-send hot motors.


[Uploading EmuFlight_0.4.2_FOXEERF722V4_Build_d177c2168_ICM42688P_MP6000_Analog.hex.zip…]()

please test/feedback any/all features applicable:
✔️/❌ Flash
✔️/❌ Gyro
✔️/❌ Accelerometer
✔️/❌ Motors
✔️/❌ Onboard ADC
✔️/❌ OSD (analog)
✔️/❌ Smart Audio controls (OSD and CLI)
✔️/❌ Alarm switch
✔️/❌ Barometer
✔️/❌ Blackbox
✔️/❌ BlueTooth (if applicable)
✔️/❌ LED
✔️/❌ GPS

**Comment by nerdCopter** [comment]
think i forgot `#define ICM42688P_EXTI_PIN          PC4`

**Comment by nerdCopter** [comment]
no feedback on these old hex, but made new code tested good by @mokshfpv.
PR #922

**Comment by nerdCopter** [comment]
@pavankmr853 able to test?
