### ISSUE TITLE
Original Splashscreen OSD ?

### ISSUE THREAD

**Issue by ochbob** [emuflight/EmuFlight#88]
Hello,

I don't know why, but I have an issue with Emuflight stock OSD Splashscreen.

Where can I found the original one ?

Thank you.

**Comment by deanrather** [comment]
I'm not one of the devs but I have been mucking around with fonts and the osd screen a bit.

I think maybe what yo u're looking for is the "default.mdm" from here https://github.com/emuflight/EmuConfigurator/tree/master/resources/osd/2


(or maybe from the adjacent "1" folder)

If you load that in using the "Load Font File" feature on the OSD tab of the configurator, that might fix it.

**Comment by ochbob** [comment]
Will try, thank you :)

**Comment by gretel** [comment]
just upload any font using the emu configurator to get an emu on ye osd!
