### ISSUE TITLE
[Target Request] DIAT_MAMBAF405_2022B (icm42688p)

### ISSUE THREAD

**Issue by DutchFPV** [emuflight/EmuFlight#892]
**Vendor/Model**
* Please provide the target name:  DIAT-MAMBAF405_2022B
* Please provide vendor and model of the FC:  Diatone `MAMBAF405 MK IV 2022B (ICM42688)`
* Please provide a link to the vendor specifications.

https://www.getfpv.com/diatone-mamba-mk4-f405-mini-flight-controller-icm42688p.html

**CLI dump or Unified Target**

https://github.com/betaflight/unified-targets/blob/master/configs/default/DIAT-MAMBAF405_2022B.config

* Please provide a CLI `dump` of **DEFAULTS** or link to unified target.
  Find the unified targets here: https://github.com/betaflight/unified-targets/tree/master/configs/default

This is for a teammate who has the FC and is ready to test and feedback asap.  Thanks!

**Comment by BeauBrewski** [comment]
Working on test target
https://github.com/emuflight/EmuFlight/pull/891

**Comment by nerdCopter** [comment]
i have a feeling that target  `DIAT_MAMBAF405_2022B` will not work, i've learned more about target making, but much more to learn. would still like feedback to know the status.

**Comment by nerdCopter** [comment]
#908

**Comment by DutchFPV** [comment]
Will do.  This is for a teammate but he's eager to get it and test it.  I'll report back with BB asap.  Thanks!

**Comment by DutchFPV** [comment]
Got an update this morning that the target is still not showing active gyro in the configurator.  Let me know if I can gather any further details for you.

**Comment by BeauBrewski** [comment]
@DutchFPV 

With BF installed, in CLI can your friend type `status` and copy/paste results back.

Other thing that would be useful is with that last hex, to send a copy of the `dump all` so we can compare the hex results to the BF config.

**Comment by nerdCopter** [comment]
@DutchFPV 
i leveled up personal knowledge, let's test this 
[EmuFlight_0.4.2_DIAT_MAMBAF405_2022B_Build_20eb01f53_Analog_needs_testing_and_feedback.hex.zip](https://github.com/emuflight/EmuFlight/files/12070467/EmuFlight_0.4.2_DIAT_MAMBAF405_2022B_Build_20eb01f53_Analog_needs_testing_and_feedback.hex.zip)

**Comment by DutchFPV** [comment]
Is that an upgraded/updated hex?  I'll see if I can get you BB from my buddy.  Sorry we had both been traveling, but should have time to do this soon.  I'll update asap

**Comment by nerdCopter** [comment]
> Is that an upgraded/updated hex? 

yes, new from scratch. i've learned a bit more since first attempts.

**Comment by DutchFPV** [comment]
The official word is it "flew beautifully".  Here's the bb he was able to capture...
[mamba_f4_ICM.zip](https://github.com/emuflight/EmuFlight/files/12100529/mamba_f4_ICM.zip)

**Comment by nerdCopter** [comment]
> The official word is it "flew beautifully". Here's the bb he was able to capture... [mamba_f4_ICM.zip](https://github.com/emuflight/EmuFlight/files/12100529/mamba_f4_ICM.zip)

Thank you both!! discord for any further needs.
