### ISSUE TITLE
[TARGET REQUEST]: MAMBAF722_2022B (ICM42688p)

### ISSUE THREAD

**Issue by BeauBrewski** [emuflight/EmuFlight#893]
**Vendor/Model**
`MAMBAF722_2022B`
 MAMBA MK4 F722 APP
 https://www.diatone.us/products/mb-mk4-f722-app-fc
 
![image](https://user-images.githubusercontent.com/85623381/188011539-cd402bb5-e414-4783-adff-7ae60b4bc798.png)

https://github.com/betaflight/unified-targets/blob/master/configs/default/DIAT-MAMBAF722_2022B.config

**Comment by BeauBrewski** [comment]
Working on test targets
https://github.com/emuflight/EmuFlight/pull/891

**Comment by nerdCopter** [comment]
duplicate of #892?

**Comment by BeauBrewski** [comment]
No, that's an F405, this is F722
