### ISSUE TITLE
[targeet request] SPEEDYBEEF405V3 BMI270

### ISSUE THREAD

**Issue by nerdCopter** [emuflight/EmuFlight#913]
* `SPEEDYBEEF405V3`
* https://github.com/betaflight/unified-targets/blob/master/configs/default/SPBE-SPEEDYBEEF405V3.config
* https://github.com/betaflight/config/blob/master/configs/SPEEDYBEEF405V3/config.h

@Moksh need HD version to test DJI 03

**Comment by BeauBrewski** [comment]
Duplicate: https://github.com/emuflight/EmuFlight/issues/901
Unless you want a separate Issue for HD request. 
@nerdCopter can you access my BMI270 targets branch? https://github.com/BeauBrewski/EmuFlight/tree/Beau_BMI270_Targets/src/main/target/SPEEDYBEEF405V3

**Comment by nerdCopter** [comment]
Thank you!
