### ISSUE TITLE
F411 are often 100% cpu

### ISSUE THREAD

**Issue by nerdCopter** [emuflight/EmuFlight#915]
* reports that F411 are often 100% fixable with pid-demon 2 or less filtering.
* suggest some logic near https://github.com/emuflight/EmuFlight/blob/c9cb676f1ed13222e80e7ee8dc00b65cb806b489/src/main/flight/pid.c#L87 to define pid-denom 2 `if defined (STM32F411xE)`

**Comment by Quick-Flash** [comment]
If we could look at where the bottlenecks are we might also be able to reduce cpu enough to allow for 8k on f411 again.

**Comment by BeauBrewski** [comment]
What's best way to check for bottlenecks?

It happened after upgrading to 0.4.0, as that is when everyone with whoops started complaining about it and the suggestion to change to 8k/4k or 4k/4k was made to get cpu <30%.

Patrick with Project Mockingbird has some tricks to run at 8k/8k still through filter/tuning setting, but FC temp alarms start going off.

**Comment by nerdCopter** [comment]
i like the idea of denom 2 as quick-fix, then experienced pilot could go 8k with custom tunes.

but it is true that finding bottleneck would be great for overall code health and probably should be done irregardless. (i dont know how either)

i know in tasks serial % is wrong, maybe a culprit :man_shrugging: 
and maybe helpful: https://github.com/emuflight/EmuFlight/pull/448
