### ISSUE TITLE
Mobile App option 

### ISSUE THREAD

**Issue by MorenoMdz** [emuflight/EmuFlight#92]
I miss having a mobile app similar to the [SpeedyBee ](https://play.google.com/store/apps/details?id=com.runcam.android.runcambf&hl=en_GB) app to configure the FW on the go, via BT, USB, etc.

I can help to create or to port an existing solution if JS is an option, React Native for example.

Let's have a discussion about it and other options that may already exist?

**Comment by 3D-pilot** [comment]
RaceDroneSoft has an EMU App for Android

**Comment by nerdCopter** [comment]
App info in #67 as well.
