### ISSUE TITLE
[TARGET REQUEST] IFLIGHT_SUCCEX_E_F7 (BMI 270)

### ISSUE THREAD

**Issue by BeauBrewski** [emuflight/EmuFlight#920]
**Vendor/Model**
`IFLIGHT_SUCCEX_E_F7`

https://pyrodrone.com/products/iflight-succex-e-mini-f7-2-6s-flight-controller 
lists it can be mpu6000 or bmi270

**CLI dump or Unified Target**
[IFLIGHT_SUCCEX_E_F7](https://github.com/betaflight/config/tree/master/configs/IFLIGHT_SUCCEX_E_F7)

Requested by JSmith on FB page

**Comment by nerdCopter** [comment]
@BeauBrewski , if you like to send to JSmith, PR with hex is here: #952
