### ISSUE TITLE
Bricked GEPRC F411 AIO Flight controller

### ISSUE THREAD

**Issue by Shreyash-Patil470** [emuflight/EmuFlight#927]
I have bricked my GEPRC F411 AIO flight controller, as in when I plug it into a PC I get a red constant light. Betaflight does not recognize that a device has been plugged in but i get no response . What do I do? 
![20230813_093653](https://github.com/emuflight/EmuFlight/assets/67952521/544bef0d-a528-46f8-b9d3-27ee0cc13558)

**Comment by nerdCopter** [comment]
https://github.com/emuflight/EmuFlight/issues/766#issuecomment-1676396468
