### ISSUE TITLE
Bricked my GEPRC-TAKER G4 35A AIO, 3 ESC's are missing

### ISSUE THREAD

**Issue by Barelfpv** [emuflight/EmuFlight#962]
i tried to flash the esc with blheli configurator and the flash failed and then i ended up missing 3 out 4 esc's.
anyone can help me with bringing them back?

**Comment by nerdCopter** [comment]
> i tried to flash the esc with blheli configurator and the flash failed and then i ended up missing 3 out 4 esc's. anyone can help me with bringing them back?

Emu does not even support G4 FC's.
recommend Betaflight discord or Joshua bardwell (or other youtube) videos on how to unbrick ESC's.  maybe can force-flash, but more likly need an arduino board and soldering for fix boot-loader.
